Offroad-iOS/Offroad-iOS.xcworkspace/contents.xcworkspacedata, Offroad-iOS/Offroad-iOS.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Offroad-iOS/Offroad-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved, Offroad-iOS/Offroad-iOS/Global/Resources/Info.plist
- #11 
FontLitera을 사용하기 위해 lable.font = UIFont.offroad(style: .title) 과 같이 사용할 수 있어야 하는데, 에러가 나는 버그 해결
-> Info.plist에 폰트를 추가할 때, 폰트 확장자까지 추가했어야 하는데, 확장자가 누락되었음. 확장자 추가함으로써 해결
- Resolved: #11
=> [Fix/#11] Info.plist에 추가된 폰트 이름에 확장자 추가

Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj, Offroad-iOS/Offroad-iOS/Global/Extensions/UIButton+.swift
- #26
기본적으로 UIButton은 배경 색상을 직접 설정할 수 없으므로, 1x1 크기의 색상 이미지를 생성하여 이를 배경 이미지로 사용하는 방식으로 배경 색상을 변경한다.
```swift
func setBackgroundColor(_ color: UIColor, for state: UIControl.State) {
UIGraphicsBeginImageContext(CGSize(width: 1.0, height: 1.0))
guard let context = UIGraphicsGetCurrentContext() else { return }
context.setFillColor(color.cgColor)
context.fill(CGRect(x: 0.0, y: 0.0, width: 1.0, height: 1.0))
let backgroundImage = UIGraphicsGetImageFromCurrentImageContext()
UIGraphicsEndImageContext()
setBackgroundImage(backgroundImage, for: state)
}
```
|뷰|설명|
=> [Add] UIButton+ 버튼 상태에 따라 backgroundColor가 바뀌는 함수 추가

Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj, Offroad-iOS/Offroad-iOS/Presentation/Nickname/View/GenderView.swift, Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/GenderViewController.swift
- #25 
3개의 버튼 중 하나만 선택할 수 있고, 버튼이 선택되면 textColor, backgroundColor, borderColor가 변경되도록 구현했다.
View와 Controller의 책임 분리를 하고, 마크주석도 추가했다.
1.
isEnabled는 버튼이 눌릴 수 있는 지의 “가능여부”이고, isSelected는 버튼의 “선택여부”이다.
```swift
@objc func buttonTapped(_ sender: UIButton) {
[genderView.maleButton, genderView.femaleButton, genderView.etcButton].forEach { button in
if button == sender {
button.isSelected.toggle()
button.layer.borderColor = button.isSelected ? UIColor.sub(.sub).cgColor : UIColor.grayscale(.gray100).cgColor
} else {
button.isSelected = false
button.layer.borderColor = UIColor.grayscale(.gray100).cgColor
}
}
}
```
2. ➕왜 함수 앞에 @objc를 붙이지?
Objective-C에서 `@selector`를 사용하여 메서드를 호출하는 경우, 해당 메서드는 `@objc` 속성으로 선언되어야 함.
`@objc`를 사용하지 않으면 Objective-C 런타임에서 해당 메서드를 찾을 수 없기 때문에 에러가 발생
|뷰|설명| …
=> [Feat] #25 - GenderViewController UI 구현

Offroad-iOS/Offroad-iOS/Presentation/Splash/View/SplashView.swift, Offroad-iOS/Offroad-iOS/Presentation/Splash/ViewController/SplashViewController.swift
- #39
SplashView에서 LoginView 전환하는 애니메이션을 구현했습니다.
- present시 Dissolve 효과를 CATransition을 활용하여 구현하였습니다.
```
private func presentLoginViewController() {
let loginViewController = LoginViewController()
loginViewController.modalPresentationStyle = .fullScreen
let transition = CATransition()
transition.duration = 0.6
transition.type = .fade
transition.subtype = .fromRight
view.window?.layer.add(transition, forKey: kCATransition)
present(loginViewController, animated: false, completion: nil)
}
```
피그마 기준으로 로고 유지시간 = 0.6초, 로고 Fade out 시간 = 0.4초, 로고 사라진 후 유지시간 = 0.4초, dissolve 시간 = 0.6초를 다음과 같이 작성했는데 뭔가.. 효율적인지 잘 모르겠어서.. 의견 주세요!!  ㅠㅠ
```
override func viewDidAppear(_ animated: Bool) {
DispatchQueue.main.asyncAfter(deadline: .now() + 0.6) {
self.rootView.dismissOffroadLogiView { …
```
=> [Feat] #39 - SplashView LoginView 화면 전환 애니메이션 구현

Offroad-iOS/Offroad-iOS/Global/Extensions/UIView+.swift, Offroad-iOS/Offroad-iOS/Presentation/Home/TitlePopup/View/TitlePopupView.swift, Offroad-iOS/Offroad-iOS/Presentation/Home/TitlePopup/ViewController/TitlePopupViewController.swift
- #51
UIView의 popup이 나타나고 사라지는 extension 함수를 구현하였습니다.
디자이너 분들과 상의 후 지속 속도를 `withDuration: 0.5` 으로 설정해두었습니다! 추후 변경이 필요하다면 파라미터로 빼두어 수정하하겠습니당
```
func presentPopupAnimation() {
transform = CGAffineTransform(scaleX: 0.5, y: 0.5)
UIView.animate(withDuration: 0.5, delay: 0, usingSpringWithDamping: 1, initialSpringVelocity: 1, options: .curveEaseInOut, animations: {
self.transform = CGAffineTransform.identity
self.alpha = 1
}, completion: nil)
}
```
`presentPopupAnimation()`의 경우 기존 View의 알파값을 0으로 지정해주어야 점차 alpha 값이 진해지면서 나타나는 구조로 작성했기 때문에, 함수를 불러오기 전에 꼭 애니메이션을 적용할 View의 alpha 값을 0으로 지정해야합니다!!
(alpha값을 해당 함수에서 0으로 설정한 뒤 애니메이션을 적용시키게 되면 기존에 투명하지 않았던 뷰가 먼저 보인뒤 애니메이션이 나타나는 형태가 보이기도 해서 위와 같이 구현하였는데.. 더 좋은 방법이 있다면 알려주십시오 ㅠ)
```
private func changeTitleButtonTapped() {
print("changeTitleButtonTapped") …
```
=> [Feat] #51 - UIView extension popup 애니메이션 구현

Offroad-iOS/Offroad-iOS/Network/Adventure/AdventureAPI.swift, Offroad-iOS/Offroad-iOS/Network/Adventure/DTO/Response/AdventureInfoResponseDTO.swift, Offroad-iOS/Offroad-iOS/Network/Auth/AuthAPI.swift, Offroad-iOS/Offroad-iOS/Network/Base/BaseService.swift, Offroad-iOS/Offroad-iOS/Network/Base/BaseTargetType.swift, Offroad-iOS/Offroad-iOS/Network/Base/NetworkService.swift, Offroad-iOS/Offroad-iOS/Network/Emblem/DTO/Response/ChangeEmblemResponseDTO.swift, Offroad-iOS/Offroad-iOS/Network/Emblem/EmblemAPI.swift, Offroad-iOS/Offroad-iOS/Network/Emblem/EmblemService.swift, Offroad-iOS/Offroad-iOS/Network/Quest/QuestAPI.swift, Offroad-iOS/Offroad-iOS/Network/Quest/QuestService.swift, Offroad-iOS/Offroad-iOS/Presentation/Home/Component/CustomAlmostDoneProgressView.swift, Offroad-iOS/Offroad-iOS/Presentation/Home/Component/CustomQuestView.swift, Offroad-iOS/Offroad-iOS/Presentation/Home/Component/CustomRecentProgressView.swift, Offroad-iOS/Offroad-iOS/Presentation/Home/TitlePopup/View/Cell/TitleCollectionViewCell.swift, Offroad-iOS/Offroad-iOS/Presentation/Home/TitlePopup/View/TitlePopupView.swift, Offroad-iOS/Offroad-iOS/Presentation/Home/TitlePopup/ViewController/TitlePopupViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Home/View/HomeView.swift, Offroad-iOS/Offroad-iOS/Presentation/Home/ViewController/HomeViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Login/ViewController/LoginViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/TabBar/ViewControllers/OffroadTabBarController.swift
- #62
HomeView 및 TitlePopupView에서 작동하는 모든 API를 연결하였습니다.
- 초기 홈 화면 로드 시 탐험 정보 불러오는 API
- 초기 홈 화면 로드 시 퀘스트 정보 불러오는 API
- 칭호 바꾸기 버튼 클릭 시 칭호 조회 API 
- 칭호 선택 후 "바꾸기" 버튼 클릭 시 변경된 칭호 서버에 전송하는 API
|칭호 바꾸기까지 전체적인 로직 실행 화면|칭호 변경 후 재접속 했을 시에 변경했던 칭호로 초기 로드되는 것 확인|
|:------------:|:--------:|
|https://github.com/user-attachments/assets/f2dd250d-d318-4220-9aac-81064c28d694|![image](https://github.com/user-attachments/assets/7bde351a-87cf-4f88-afde-c9b6958a68cb)|
|탐험 정보 GET 요청|퀘스트 정보 GET 요청|
|:------:|:--------:|
|<img width="199" alt="image" src="https://github.com/user-attachments/assets/2be94bd3-8a32-4306-ac7b-041896c7e57d">|<img width="164" alt="image" src="https://github.com/user-attachments/assets/b69071c7-3e30-454d-b162-454ab23fa3a1">|
|탐험 정보 응답|퀘스트 정보 응답|
|:------:|:------:|
|<img width="245" …
=> [Feat] #62 - HomeView API 통신

Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
- #92 
뒤로가기를 눌렀을 때 다음 버튼이 계속 활성화되는 이슈 발생
viewWillApppear에 버튼 isDisabled 코드를 넣으면 VC로 이동할 때마다 버튼이 비활성화되고,
중복확인을 해야지만 버튼이 활성화된다.
|뷰|설명|
- Resolved: #92
=> [Feat] #92 - 백버튼 눌렀을 때 다음 버튼 비활성화

Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj, Offroad-iOS/Offroad-iOS/Network/Adventure/DTO/Response/AdventureInfoResponseDTO.swift, Offroad-iOS/Offroad-iOS/Network/Base/BaseTargetType.swift, Offroad-iOS/Offroad-iOS/Presentation/Character/ChoosingCharacter/ViewController/ChoosingCharacterPopupViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Login/AuthManager/KeychainManager.swift, Offroad-iOS/Offroad-iOS/Presentation/Login/ViewController/LoginViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Splash/ViewController/SplashViewController.swift
- #105 
- 기존에 토큰, 사용자 이름 등을 UserDefault에 저장했던 방식을 Keychain을 사용하는 방식으로 변경하였습니다!
```
private func postTokenForAppleLogin(request: SocialLoginRequestDTO) {
NetworkService.shared.authService.postSocialLogin(body: request) { response in
switch response {
case .success(let data):
let accessToken = data?.data.tokens.accessToken ?? ""
let refreshToken = data?.data.tokens.refreshToken ?? ""
KeychainManager.shared.saveAccessToken(token: accessToken)
KeychainManager.shared.saveRefreshToken(token: refreshToken)
```
- 로그인 이력도 키체인에 저장하게 되면 앱을 삭제했다 다시 깔아도 자동 로그인이 되기 때문에 한 번의 로그인 과정을 거칠 수 있도록 UserDefault에 저장하였고, 다시 로그인을 하면 로그인 이력이 저장되게 됩니다.
```
AppleAuthManager.shared.loginSuccess = { user, identifyToken in
print("login success!")
UserDefaults.standard.set(true, forKey: "isLoggedIn")
```
- 서버측과 논의하여 같은 …
=> [Fix] #105 - Keychain을 사용한 로그인 로직 수정

Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/BirthViewController.swift
- #112 
"년"이 유효한 4자리수고 "월"이 유효한 2자리수일 때 다음 textfield로 자동 이동하도록 구현했다.
**@objc func textFieldDidEndEditing**를 통해 “월” textfield에서 “1”만 입력하고 다른 곳을 누르면 사용자 화면에 “01”로 바뀌도록 구현했다.
```swift
@objc internal func textFieldDidEndEditing(_ textField: UITextField) {
if textField == birthView.monthTextField {
if let monthText = birthView.monthTextField.text, monthText.count == 1 {
birthView.monthTextField.text = "0\(monthText)"
}
} else if textField == birthView.dayTextField {
if let dayText = birthView.dayTextField.text, dayText.count == 1 {
birthView.dayTextField.text = "0\(dayText)"
}
}
}
```
|뷰|설명|
- Resolved: #112
=> [Fix] #112 - 생년월일 자동이동 및 자동변환

Offroad-iOS/Offroad-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved, Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/PlaceInfoPopupViewController.swift
- #114 
- 공원 탐험 성공 시 팝업이 뜨지 않는 문제를 해결하였습니다.
- ### 저도 드디어 Xcode 및 Swift 버전을 업데이트하여 Package.resolved의 버전이 3이 되었습니다!!!  
- 파일 변경 내용 중 Package.resolved 파일이 있으며,  
이는 제 Xcode의 버전이 올라가면서 2->3으로 바뀌며 생긴 현상으로, 충돌이 아니니 걱정 마세요!
|뷰|설명|
| <img src="https://github.com/user-attachments/assets/7b5e8558-22c4-4e53-b41b-82786bedab00" width="200"/> | <img src="https://github.com/user-attachments/assets/9d82e783-788c-4c51-93f1-4a6abf1b9249" width="200"/> |
| 공원 탐험에 성공했을 시 뜨는 팝업 | 홈 화면으로 이동 시 뜨는 로티 화면 |
- Resolved: #114
=> [Fix/#114] 공원 탐험 성공 시 팝업이 뜨지 않는 문제 해결

Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/DeleteAccount/ViewController/DeleteAccountViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/Logout/ViewController/LogoutViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Splash/ViewController/SplashViewController.swift
- #170
로 그아웃 이벤트 구현
- 로그아웃 시 로그인 이력을 저장하는 Userdefault와 KeyChain에 저장되어있는 토큰 정보를 삭제하였습니다.
- 로그아웃 이후 스플래시 뷰로 이동하도록 하였습니다.
|iPhone 15 Pro|
|:------:|
|<img src="https://github.com/user-attachments/assets/0b59d195-aa92-4059-a91e-8eab080892f7" width="393px"/>|
- Resolved: #170
=> [Feat] #170 - 로그아웃 이벤트 구현

Offroad-iOS/Offroad-iOS/Global/Extensions/UILabel+.swift
- #175 
- 스타일 가이드의 font에 Line Height가 설정되어 있을 경우, (행간이 백분율로 표시) 
지금까지는 디자이너로부터 얼마큼 `lineSpacing`을 주어야 하는지 그 값을 직접 받아 적용하였음.
- 디자이너로부터 매번 값을 전달받아 적용하기 번거로워 이를 개선하였음
- 백분율 값을 이용할 수 있도록 추가적인 함수를 UILabel에 확장 구현하였습니다. 
- 추가된 메서드의 이름은 `setLineHeight(percentage:)` 입니다.
- UIFont의 속성 중 `ascender`와 `descender`를 이용하여 필요한 값을 계산하였습니다. 
맞게 적용했음에도 UILabel 상에서 텍스트의 세로 위치가 아주 약간 다르게 보이는 상황이 있습니다. 
이 경우에는 UILabel의 높이를 명시적으로 설정해 주어야 합니다. 
원래는 UILabel에서 자체적으로 자체 크기를 설정하는데, 
피그마에서 명시적으로 크기(특히 높이)를 설정할 경우 이를 코드에도 명시적으로 적용해 주면 
피그마와 완전히 동일한 UI를 구현할 수 있습니다. 
|뷰|설명|
- Resolved: #175
=> [Feat] #175 - LineHeight %값으로 적용할 수 있도록 UILabel 확장 함수 추가

Offroad-iOS/Offroad-iOS/Global/Extensions/UILabel+.swift
- #177 
setLineSpacing(spacing:), setLineHeight(percentage:) 함수에서, textAlignment등 과 같은 속성을 style에 적용하여 이를 attributedString에 적용하는 식으로 구현하여,
UILabel의 속성(textAlignment 등)에 값을 할당해도 적용하지 않는 문제 발생
즉, 어떤 UILabel인스턴스의 textAlignment 속성을 .center로 할당해도, setLineSpacing이나 setLineHeight와 같은 함수를 사용하면 textAlignment가 적용되지 않는 문제 발생. 
이를 해결하기 위해 확장 함수 내의 style 의 일부 속성에 UILabel의 속성값을 그대로 할당하였음. 
|뷰|설명|
- Resolved: #177
=> [Fix] #177 - setLineSpacing(spacing:), setLineHeight(percentage:) 함수 수정

Offroad-iOS/Offroad-iOS/Network/Place/DTO/Responce/RegisteredPlaceResponseDTO.swift, Offroad-iOS/Offroad-iOS/Presentation/PlaceList/Models/PlaceListDummyDataManager.swift, Offroad-iOS/Offroad-iOS/Presentation/PlaceList/ViewControllers/PlaceListViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/PlaceList/Views/PlaceCollectionViewCell.swift, Offroad-iOS/Offroad-iOS/Presentation/QuestList/Views/QuestListCollectionViewCell.swift
- #190
- QA 수정사항은 반영하였습니다. 
- 장소 목록 뷰
- 장소 구역(예, 시간이 머무는 마을) 표시 라벨의 데이터를 받아올 수 있도록 구현하였습니다.   
(기존에는 서버 응답 데이터에 해당 데이터가 없어 "장소 섹션 라벨(임시)" 라는 문자열리터럴을 입력했었습니다.)
- 퀘스트 목록 뷰
- 퀘스트 목록 뷰의 셀 내부 UI를 개선하였습니다.   
(데이터가 없을 경우 셀의 내부가 좁게 보이는 현상을 개선하였습니다. 
- 퀘스트 목록 뷰의 셀에 데이터가 없을 경우 "데이터 없음" 데이터를 띄우도록 empty case를 추가하였습니다.   
(현재 서버의 응답 데이터에 퀘스트 설명, 달성 조건, 보상 등이 빈 문자열로 오기 때문에, 해당 기능을 추가했음)
empty case와 관련해서는 추후 기획-디자인 논의가 끝난 후 정해지는 내용에 따라 변경될 가능성이 높습니다. 현재 임시로 구현한 것으로 봐 주시면 될 것 같습니다. 
- main 브랜치의 최신사항을 반영하는과정에서 커밋 이름에 [Merge/# 190] 이 들어가야 하는 걸 실수로 [Merge/# 174] 라고 들어가 버렸네요..(d3483316a33ae07577caefe2a82d34371be9f4ac)
ㅠ__ㅠ  
헷갈리지 마시라고 알려드립니다...!
|    |  장소 목록 뷰 | 퀘스트 목록 뷰  |
|:--:|:---:|:---:|
| 뷰 |  <img src="https://github.com/user-attachments/assets/3de9b6e9-1ee1-43bb-8ac8-99c2f2b450e7" width=200>  | …
=> [Fix] #190 - QA 수정사항 반영

Offroad-iOS/Offroad-iOS/Global/Components/PopupController/OFRAlertController.swift, Offroad-iOS/Offroad-iOS/Network/Coupon/CouponService.swift, Offroad-iOS/Offroad-iOS/Network/Coupon/DTO/Response/CouponListResponseDTO.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/View/AcquiredCouponView.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/AcquiredCouponViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/CouponDetailViewController.swift
- #204 
- ~서버에서 쿠폰 적용 API 수정이 완료되지 않아, 쿠폰 적용 API를 붙이지는 못했고,   
대신 테스트용 함수를 추가하여 이를 바탕으로 쿠폰 사용 로직을 구현하였습니다.~
-> 정기 회의 후 쿠폰 적용 API의 수정된 내용을 반영하였습니다. 
- 팝업이 사라질 때 로직을 일부 수정하였습니다. 
- 버튼이 눌리면 실행될 함수(클로저)를 dismiss가 완료된 후의 시점으로 변경  
(기존에는 dismiss 되기 전에 실행했음)
- 팝업이 사라지는 애니메이션 속도를 수정하였습니다. 
- 쿠폰 번호 입력을 누르고 서버 통신(지금은 테스트 함수)을 통해 다음 팝업으로 피드백이 뜨는 과정을 RxSwift로 구현하였습니다. 
- 이 부분은 추후 개선하여 MVVM 아키텍처로 구현하면 좋을 것 같습니다. 
- ~테스트용으로 만든 거라, 현재는 쿠폰 코드가 0000일 경우 사용이 완료되었다고 뜨고,   
0000이 아닌 다른 모든 코드는 사용이 실패했다고 뜹니다. 잘 작동되는지 확인 바랍니다.~
-> 정기 회의 후 쿠폰 적용 API 변경된 부분 적용하여 0000을 입력해도 실패했다고 뜹니다. 정확한 쿠폰 코드를 입력해야 합니다. 
- 쿠폰 사용이 실패했을 때 메시지 옆에 뜨는 느낌표 모양의 아이콘은 구현하지 못했습니다.  
이는 추후 팝업 틀이 완료되면 반영하여 구현하면 좋을 것 같습니다. 
|뷰|설명|
|  <img src="https://github.com/user-attachments/assets/efe84461-94d3-48ad-9910-19e2e27a38cd" …
=> [Feat] #204 - 쿠폰 적용 API 연결(시도) 및 연속 팝업 구현

Offroad-iOS/Offroad-iOS/Global/Extensions/UIScreen+.swift, Offroad-iOS/Offroad-iOS/Presentation/TabBar/ViewControllers/OffroadTabBarController.swift, Offroad-iOS/Offroad-iOS/Presentation/TabBar/ViewControllers/OffroadTabBarViewController.swift
- #222 
현재 탭바의 높이를 92로 고정한 상황입니다. 
홈 버튼이 있는 기기의 경우, 탭바의 높이가 92이면 부자연스럽게 커 보여서, 
홈 버튼이 있는 기기의 경우 탭바의 높이를 살짝 낮추어(60) 보다 자연스러워 보일 수 있도록 구현하였습니다. 
- 스크린샷에서 볼 수 있듯, 현재 홈 버튼이 있는 기기의 화면 비율에서는 UI 일부가 잘리거나 맞지 않는 현상이 발생합니다. 
이에 대한 대응을 하면 좋으나, 현재는 홈 버튼이 있는 기기에 맞게 UI 작업하는 것은 후순위로 미루어진 상태이므로, 
지금 당장 수정할 필요는 없습니다. 
(마이페이지에서 아래 선택 항목들만 스크롤이 되도록 구현되어 있는데, 마이페이지 전체가 스크롤 되는 것이 더 깔끔할 것 같아 보여 이 부분은 제가 별도의 브랜치를 생성하여 구현할 예정입니다. )
- 앞서 언급한대로 홈 버튼이 있는 기기 화면 비율에 맞게 대응하는 것은 후순위의 작업입니다. 
따라서 이 때의 탭바 높이인 60 역시 제가 임의로 설정한 것으로, 추후 디자이너분들이 작업하시면서 변경될 수 있습니다. 
이 브랜치에서의 작업은 홈 버튼이 있는 기기인지 확인하는 데에 그 목적이 있다고 생각해 주시면 될 것 같습니다. 
|뷰|설명|
| <img src="https://github.com/user-attachments/assets/2c31df36-c678-460e-ba15-582c8a572885" width=200> |     |
- Resolved: #222
=> [Feat] #222 - 기기 화면 비율에 따른 분기처리

Offroad-iOS/Offroad-iOS/Presentation/TabBar/ViewControllers/OffroadTabBarController.swift
- #253 
탭바 버튼 중 My 탭을 누를 시, 한 번에 버튼 색이 밝아지지 않고, 버튼의 색이 일시적으로 어둡거나, 한 번 더 누를 때까지 밝은 색으로 뜨지 않는 문제를 해결하였습니다.
이를 위해 탭바가 올라왔는지 여부를 저장하는 `isTabBarShown`이라는 `flag` 를 만들었습니다. 
| 수정 전 | 수정 후 |
|  <img src="https://github.com/user-attachments/assets/e0952d4d-71f5-475d-9ba6-42ab5424c09f" width=200>     |  <img src="https://github.com/user-attachments/assets/194e4360-e283-4b90-a6f9-1ce2468d2c78" width=200>    |
- Resolved: #253
=> [Fix] #253 - 탭바 눌렀을 때 item이 바로 선택되지 않던 문제 해결

Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj, Offroad-iOS/Offroad-iOS/Global/Components/AppUtility.swift, Offroad-iOS/Offroad-iOS/Network/Auth/AuthService.swift, Offroad-iOS/Offroad-iOS/Presentation/Login/AuthManager/TokenIntercepter.swift
- #263
리프레시 토큰을 재발급하는 로직을 구현하였습니다.
리프레시 토큰이 만료되면 해당 에러가 발생하면서 멈추게 되는데 이 때 LoginViewController로 이동하도록 하였습니다.
- 프로젝트 전역해서 사용할 수 있도록 AppUtility 클래스를 작성하고 rootViewcontroller를 변경해주는 함수를 작성하였습니다.
```
final class AppUtility {
static let shared = AppUtility()
private init() {}
static func changeRootViewController(to viewController: UIViewController) {
let window = UIWindow.current
DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
UIView.transition(with: window, duration: 1.0, options: .transitionCrossDissolve, animations: {
window.rootViewController = viewController
}, completion: nil)
window.makeKeyAndVisible()
}
}
}
```
커밋에 이슈번호를 잘못 포함하여 해당 이슈에서는 커밋 이력이 중복되어 보일 수 있습니다..! 이 점 양해해주세요..!!
- Resolved: #263
=> [Feat] #263 - 리프레시 토큰 재발급 로직 구현

Offroad-iOS/Offroad-iOS/Network/Notice/DTO/Response/NoticeResponseDTO.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/Notice/NoticePost/View/NoticePostView.swift
- #271
- 기존에는 서버에서 링크 제목을 넘겨주지 않아서 임의로 "링크 열기"라는 제목으로 UIbutton의 title을 설정했으나, 서버에서 링크 제목을 넘겨주는 방식으로 변경되었기 때문에 반영하였습니다.
++ 추가적으로 기존 날짜 포맷팅 방식에서, `ISO8601DateFormatter`를 사용하였으나 서버에서 넘겨준 문자열이 ISO 8601 형식과 완전히 일치하지 않아 nil값으로 넘어가게 되고, 그에 따라 항상 현재 날짜가 표기되는 버그를 발견하여 이를 해결하였습니다.
|iPhone 16 Pro|
|:------:|
|<img src="https://github.com/user-attachments/assets/e34aecbc-191a-4b76-a76c-d8ede2d4650c" width="300px"/>|
- Resolved: #271
=> [Fix] #271 - 공지사항 API 수정사항 반영

Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj, Offroad-iOS/Offroad-iOS/Global/Components/Overlay/Loading/LoadingView.swift, Offroad-iOS/Offroad-iOS/Global/Extensions/UIView+.swift, Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/QuestMapViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewModel/QuestMapViewModel.swift
- #281 
로딩 뷰를 구현했습니다. 
UIView의 확장으로 함수를 만들어 구현했습니다. 
사용법은 매우 간단합니다. 
로딩을 표현하고자 하는 뷰에서 로딩 시작, 끝 시점에 각각 `startLoading()`, `stopLoading()` 메서드를 호출하면 됩니다. 
예를 들어, 네트워크 API를 호출하는 시점에 원하는 뷰에서 `startLoading()` 메서드를 호출하고, 네트워크 통신이 끝난 시점에 `stopLoading()` 메서드를 호출하면 됩니다. 
만약 탭바까지 로딩 화면으로 덮고 싶다면, 탭바컨트롤러에 접근하여 탭바컨트롤러의 뷰에서 해당 메서드들을 호출하면 됩니다. 
잘 동작하는지 확인하기 위한 예시로, 지도 뷰에서 로딩 화면을 적용하였습니다. 
*지도 뷰에 로딩 화면 적용하면서, 로직도 일부 개선하였습니다.
|뷰|설명|
|   <img src="https://github.com/user-attachments/assets/79d26850-0355-401f-ab0e-13efb34adac5" width=200>   |     |
- Resolved: #281
=> [Feat] #281 - (로티가 화면 중앙에 오는) 로딩 뷰 구현

Offroad-iOS/Offroad-iOS/Global/Extensions/UIView+.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/Cell/CharacterListCell.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/View/CharacterDetailView.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/View/CharacterListView.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewController/CharacterDetailViewController.swift
- #285 
- 캐릭터 관련 뷰의 UI를 개선하였습니다. 
- 캐릭터 이미지에 로딩 로티를 추가하였습니다. 
- 캐릭터 이미지에 로딩 로티를 추가하기 위해, UIView에서 로딩 화면을 구현하는 확장 함수에 매개변수를 추가하였습니다. 
추가된 매개변수는 withoutShading(Bool 타입) 이며 기본값은 false입니다. 해당 매개변수를 true로 설정할 시 어두워지는 효과 없이 로딩 로티만 화면에 뜨게 됩니다. 
https://github.com/user-attachments/assets/60984dad-e644-4a16-98b9-2f41af4e372c
|뷰|설명|
- Resolved: #285
=> [Chore] #285 - 캐릭터 관련 뷰 UI 개선

Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj, Offroad-iOS/Offroad-iOS/Global/Extensions/UIImageView+.swift, Offroad-iOS/Offroad-iOS/Global/Literals/StringLiterals.swift, Offroad-iOS/Offroad-iOS/Global/Protocols/SVGFetchable.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/ORBCharacterChatManager.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/ORBCharacterChatViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/ViewControllers/CharacterChatLogViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Home/View/HomeView.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewController/CharacterDetailViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewController/CharacterListViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/Notice/ViewController/NoticeViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/View/MyPageView.swift, Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/BirthViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/PlaceList/ViewControllers/PlaceListViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/QuestMapViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/QuestQR/ViewControllers/QuestQRViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Splash/ViewController/SplashViewController.swift
- #270 
- StringLiterals 파일 추가 및 일부 적용
- 캐릭터한테 먼저 채팅 시작하기 위해 키보드 올라올 때 캐릭터 채팅 박스 일부가 보이던 문제 해결
- 채팅 로그 뷰 로딩 시 화면이 깜박거리는것처럼 보이던 문제 해결
- HomeView UI 개선 (캐릭터 이미지 크기 동적으로 조절)
- 마이페이지 프로필 이미지 사진 비율 조정
- svg, png 형식과 무관하게 이미지 파일 받아올 수 있도록 구현
지금은 SVG 받아오는 함수 로직만 일부 변경한 거라서, 추후 더 정교하고 광범위하게 개선할 예정입니다. 이 점 참고해 주세요~!
다음과 같이 투명한 배경의 png 이미지를 잘 받아오는 것을 확인할 수 있었습니다.
예시 이미지 링크는 다음과 같습니다.
[예시 이미지](https://www.apple.com/kr/iphone-16/c/images/overview/welcome/hero_alt__ey5khbzf04eq_large_2x.png)
| UIImageView의 확장 함수를 사용하는 경우 | SVGFetchable 프로토콜을 사용하는 경우  |
|   <img src="https://github.com/user-attachments/assets/8cdfd662-4970-4bf5-9e61-b7ff90addd22" width=200> | <img src="https://github.com/user-attachments/assets/e49dc7d3-d8a2-4803-bd75-5203c385ee8f" width=200> |
- Resolved: #270
=> [Fix] #270 - 버그 일부 수정, png/svg 형식 무관하게 이미지 받아오도록 구현

Offroad-iOS/Offroad-iOS/Presentation/Home/View/HomeView.swift
- #316
로티 화면이 홈 화면의 다른 버튼을 가려 터치가 제한되는 문제를 해결하였습니다. 
로티 화면이 화면 우측 상단에 들어가는 버튼들(buttonStackView)보다 더 위의 계층에 위치해서 터치 이벤트를 가로채는 현상이 있어, buttonStackView의 계층 구조를 로티 이미지 및 기본 캐릭터 이미지보다 더 위로 오도록 설정하였습니다. 
|뷰|설명|
- Resolved: #316
=> [Fix] #316 - 홈 뷰 컴포넌트들의 계층 변경

Offroad-iOS/Offroad-iOS/Application/AppDelegate.swift
- #307 
캐릭터 목록 뷰에 처음 진입 시, 캐릭터 이미지가 이상하게 뜨는 현상이 있었습니다. 
주로 앱을 시작하고 바로 캐릭터 목록 뷰에 진입하였을 때 캐릭터 목록의 이미지들이 이상하게 뒤죽박죽되는 현상입니다. 
원인은 `NetworkMonitoringManager`와 관련이 있었음을 확인하였습니다. 
해당 객체는 앱 내에서 네트워크 변경을 감지하기 위해 구현했던 싱글톤 객체인데, 
`PublishSubject`를 이용하여 네트워크 변경 시에 이를 감지하여 관련 토스트를 띄우는 역할을 하였습니다. 
캐릭터 목록 뷰에서 처음 이 Subject를 구독하게 되는데, 이 시점에 싱글톤 객체에도 처음 접근하기 때문에, 싱글톤 객체가 이때 생성되게 되고, 
이로 인해 캐릭터 목록 뷰에서 처음 캐릭터 목록을 보내는 API를 (의도치 않게) 두 번 호출하여 짧은 시간 내에 `reloadData()`가 중복으로 호출되게 됩니다. 
문제는 컬렉션뷰가 reload된 후에 얻는 이미지 URL을 이용하여 각 셀은 다시 자신의 이미지를 네트워크 통신을 통해 가져오게 된다는 점입니다. 
각 셀에서 이미지를 가져오는 통신을 하던 중에 `reloadData()`가 한 번 더 호출되면서 셀이 재사용되게 되고, 이때 셀이 재정렬되면서 객체의 순서가 바뀌는 경우 이미지 역시 뒤죽박죽되는 현상이 발생하게 됩니다. 
이를 해결하기 위해 앱 시작 시에 `NetworkMonitoringManager` 싱글톤 객체 생성함으로써, 
캐릭터 목록 뷰에서 `NetworkMonitoringManager` 객체를 생성하지 않아 `reloadData()`를 …
=> [Fix] #307 - 캐릭터 목록 뷰에 처음 진입 시, 캐릭터 이미지가 이상하게 뜨는 현상 해결

Offroad-iOS/Offroad-iOS/Presentation/Home/TitlePopup/View/TitlePopupView.swift, Offroad-iOS/Offroad-iOS/Presentation/Home/TitlePopup/ViewController/TitlePopupViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Home/ViewController/HomeViewController.swift
- #320 
홈 화면의 칭호 변경 팝업 관련 문제를 수정하였습니다. 
- 칭호 변경 팝업이 떴을 때, 탭바의 다른 탭을 누를 수 있던 문제를 해결하였습니다. 
- 칭호 변경 팝업에서 다른 칭호를 선택해도 기존 칭호가 계속 선택되어있던 것처럼 보이던 문제를 해결하였습니다. 
|뷰|설명|
|   <img src="https://github.com/user-attachments/assets/de163884-6a1f-41a8-861a-d2eacdb834bf" width=200>   |     |
- Resolved: #320
=> [Fix] #320 - 홈 화면의 칭호 변경 팝업 관련 문제 수정

Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/ViewControllers/ORBCharacterChatViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/ViewControllers/CharacterChatLogViewController.swift
- #299 
캐릭터에게 채팅을 보내고 난 후, 답장이 오기 전까지 전송 버튼을 비활성화해야 합니다. 
지금은 해당 로직이 구현되어있지 않아서, 이를 구현하였습니다.
|캐릭터 채팅 시|채팅 로그|
|     <img src="https://github.com/user-attachments/assets/e56ab5d1-ddd9-4dc7-b008-d1a0c1af3b0a" width=200>   |   <img src="https://github.com/user-attachments/assets/2ed6ef86-2fc1-407a-b236-6be4ce3175f4" width=200>  |
- Resolved: #299
=> [Feat] #299 - 전송 버튼 누른 후 캐릭터 답장 오기 전까지 전송 버튼 비활성화

Offroad-iOS/Offroad-iOS/Network/Base/BaseService.swift, Offroad-iOS/Offroad-iOS/Network/Base/NetworkResult.swift, Offroad-iOS/Offroad-iOS/Network/CharacterChat/CharacterChatService.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/ViewControllers/ORBCharacterChatViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/ViewControllers/CharacterChatLogViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/Views/ReusableView/CharacterChatLogCell.swift
- #324 
캐릭터 채팅 API를 사용할 때, 응답의 길이가 너무 길어져서 서버에서 에러가 나 500대 에러를 발생하는 이슈가 있습니다. 
이 경우에 대해 별도의 에러처리가 없어서 이를 반영하였습니다. 
서버에서 500에러가 났을 경우, "오브가 답변하기 힘든 질문이에요, 다른 이야기를 해볼까요?" 라는 토스트를 띄우게 됩니다. 
추가로 채팅 뷰일 경우 캐릭터 채팅 박스가 올라가고, 채팅 로그 뷰일 경우, 캐릭터가 답장하던 말풍선이나 내가 직전에 보냈던 채팅 기록을 지우게 됩니다. 
이를 구현하기 위해, `NetworkResult` 타입에 `serverErr` 케이스를 추가하였으며, 
BaseService의 메서드인 `fetchNetworkResult`의 경우 NetworkResult 타입을 반환하므로, status별 반환 케이스에 500 에러를 추가하였습니다. 
답변이 길어서 서버의 에러가 나는 경우는 답변이 길 것 같은 질문을 하면 되는데, 
"대표적인 CS 면접질문 10개만 뽑아줘."
라고 보낼 경우 (지금까지는) 100% 확률로 서버 에러가 발생했습니다. 
이를 통해 인위적으로 서버 에러를 일으킬 수 있으므로 테스트를 하고자 할 경우, 해당 문구를 보내면 될 것 같습니다. 
|채팅 뷰|채팅 로그 뷰|
|    <img src="https://github.com/user-attachments/assets/b9d12c87-9dcd-43c3-9402-a96a99dc6c1c" width=200>    |   <img …
=> [Fix] #324 - 캐릭터 채팅 API 중 500에러 대응

Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewController/CharacterListViewController.swift
- #312 
캐릭터 목록 뷰에서, 획득하지 않은 캐릭터를 탭 했을 때, 캐릭터 상세 뷰로 넘어가는 이슈가 있었습니다. 
이를 해결하기 위해, 획득하지 않은 캐릭터의 경우는 select될 수 없도록 구현하였습니다. 
|뷰|설명|
- Resolved: #312
=> [Feat] #312 - 캐릭터 목록 중 획득하지 않은 캐릭터 탭 제한

Offroad-iOS/Offroad-iOS/Global/MyInfoManager/MyInfoManager.swift, Offroad-iOS/Offroad-iOS/Presentation/Home/ViewController/HomeViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewModel/CharacterDetailViewModel.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/QuestMapViewController.swift
- #327 
현재 홈 뷰 마이페이지에서는 뷰가 보일 때마다 매번 새로 데이터를 받아오고 있습니다.
`viewWillAppear()` 메서드에서 API를 사용하여 서버와 통신하는 식인데요,
이 때문에, 내비게이션 스택에서 pop을 하려고 제스처를 사용할 때, 일시적으로 화면이 깜박거리는 것 처럼 보입니다.
(사실 로딩으로 인해 화면이 어두워졌다 밝아지는 것인데, 사용자 입장에서는 찰나의 순간이라 깜박거리는 것 처럼 보일 수 있습니다. )
그래서 이 부분에 대한 문제를 근본적으로 해결하고자, 로직을 수정하였습니다. 
방법은 "정보가 업데이트될 때만 서버로부터 새 데이터를 받아온다" 입니다. 
지금은 같은 정보를 계속 새로 받아오고 있는 상황이라서 이를 개선하고자 하였습니다. 
이전에 만들어 놓은 `MyInfoManager`라는 싱글톤 객체가 있습니다. 
이 객체는 현재 대표 캐릭터의 이름을 저장하는데요 (채팅 로그 뷰에서 현재 대표 캐릭터의 이름을 알아야 하기 때문에...)
이 객체 안에서 RxSwift로 이벤트를 전달할 속성들을 일부 추가하였습니다. 
그리고 탐험 정보나 캐릭터 정보가 변경될 때마다 이 Relay들을 통해 탐험 정보나 캐릭터 정보가 변경되었다는 소식을 `MyInfoManager`로 전달하고, 
홈 화면이나 마이페이지에서는 이들 Relay를 구독하고 있다가 변경점이 생길 경우에 한해서 데이터를 업데이트 하게 됩니다. 
이러한 방식은 캐릭터 변경이나 탐험 성공 시 화면에 반영되는 정보가 즉각적으로 업데이트된다는 장점이 있으며, 
이 외에도 매번 화면이 보일 때마다 로딩을 진행하던 전에 비해 서버 …
=> [Fix] #327 - 홈 뷰와 마이페이지의 새로고침 로직 개선

Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj, Offroad-iOS/Offroad-iOS/Global/Extensions/UICollectionView+.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/ViewControllers/CharacterChatLogViewController.swift
- #334 
채팅에 실패할 경우 (예를 들어 답변이 길어져서 서버에서 500대 에러가 난 경우) 
채팅 로그 뷰에서는 채팅에 실패한 말풍선을 삭제해야 합니다.
이때 가장 최근의 말풍선 2개(캐릭터 로딩 말풍선과 직전에 내가 보낸 말풍선) 를 제거해야 하는데, 
삭제 후 collectoinView의 마지막 섹션이 여전히 존재하는 경우 에러가 발생하며 앱이 꺼지게 됩니다.
(예를 들어, 오늘 처음 메시지를 보낸 경우, 마지막 섹션이 추가되며  item이 추가되는데, 삭제 시에는 item만 삭제되고 section은 삭제되지 않은 상황)
이때, 변경된 dataSource에는 해당 섹션이 남아있지 않아서 에러를 일으키는 것을 확인하였고, 이를 해결하였습니다.
- 주로 변경된 코드는 `ChracterChatLogViewController`의 `updateChatLog(chatSuccess:)` 메서드이며, 아이템이 삭제될 때 마지막 섹션이 비어있거나 DataSource가 빈 데이터인 경우 마지막 섹션을 지우도록 구현하였습니다. 
-  UICollectionView의 item들 중 마지막에서 n번째 `IndexPath`를 반환하는 확장 함수를 구현하였습니다. 
이를 위해 `UICollectionView+.swift` 파일을 추가하였으며, `getIndexPathFromLast(index:)` 메서드를 구현하였습니다. 
- 만에 하나 IndexPath를 제대로 불러오지 못하는 경우, 컬렉션뷰는 `reloadData()`를 호출하도록 구현하였습니다. 
테스트를 위해서는 채팅 로그가 없는 빈 채팅 로그, 혹은 오늘 처음 …
=> [Fix] #334 - 채팅 실패 시 말풍선 사라지는 로직 개선

Offroad-iOS/Offroad-iOS/Global/Components/NavigationController/ORBNavigationController.swift, Offroad-iOS/Offroad-iOS/Network/CharacterChat/CharacterChatAPI.swift, Offroad-iOS/Offroad-iOS/Network/CharacterChat/CharacterChatService.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/ORBCharacterChatManager.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/ViewControllers/ORBCharacterChatViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/ViewControllers/CharacterChatLogViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/View/CharacterDetailView.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewController/CharacterDetailViewController.swift
- #306 
- 캐릭터와 채팅 시 캐릭터 ID별로 원하는 캐릭터에게 채팅을 보낼 수 있도록 구현하였습니다.
이를 통해 채팅 로그 뷰에서 "채팅 로그" 버튼을 누르면, 각 캐릭터에 해당하는 채팅 로그가 뜨도록 구현하였습니다. 
- 채팅 로그 뷰에서 "채팅하기" 버튼이 올라가고 내려가는 로직을 개선했습니다. 
원래는 컬렉션뷰 콘텐츠의 가장 아래쪽이 보일 때 딱 맞춰서 버튼이 내려가고 올라가게 구현했었는데, 
길이를 계산하는 과정에서 소수점이 안 맞았는지, 가장 아래로 스크롤했을 때에도 버튼이 자동으로 내려가는 현상을 발견하였고, 이를 수정하였습니다. (컨텐츠 끝에서 버튼이 내려가던 이전과 달리, 가장 아래에서 20포인트만큼 위로 스크롤한 경우 버튼이 내려갑니다.)
|뷰|설명|
|   <img src="https://github.com/user-attachments/assets/71df7402-b314-416c-a7bb-69284f33a14f" width=200>    |     |
- Resolved: #306
=> [Fix] #306 - 캐릭터 채팅 시 원하는 캐릭터 ID별로 채팅 요청하는 기능 구현

Offroad-iOS/Offroad-iOS/Presentation/Splash/ViewController/SplashViewController.swift
- #348 
SplashViewController에서 로그인 전 캐릭터 정보를 요청하는 코드가 있었고, 
refreshToken 만료 시에 이 코드가 요청 응답에 실패하면 이로 인해 로그인이 진행되지 않는 문제를 발견하였습니다. 
이를 해결하기 위해 SplashViewController에서 캐릭터 정보를 요청하는 코드를 로그인 성공 이후로 옮겼습니다. 
|뷰|설명|
- Resolved: #348
=> [Fix] #348 - refreshToken 만료 시 로그인이 되지 않던 문제 해결

Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/Cell/CharacterListCell.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/View/CharacterListView.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/Cell/CouponCell.swift, Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewModel/QuestMapViewModel.swift
- #346 
- 캐릭터 목록 뷰와, 쿠폰 목록 뷰의 컬렉션 뷰 셀에서 탭 시 쉐이딩되는 효과를 구현하였습니다. 
- 지도에서 데이터가 불러오지 않는 것을 확인하고, 지도에서 장소 목록을 요청 시 isBounded = false 로 임시로 설정하였으며, 추후 API가 변경 시에 수정된 API를 적용할 예정입니다. 
|뷰|설명|
|    <img src="https://github.com/user-attachments/assets/3e2b3fbe-7678-4b68-b73d-1a9764570f3c" width=200>    |     |
- Resolved: #346
=> [Feat] #346 - 셀 선택 시 탭 피드백 적용

Offroad-iOS/Offroad-iOS/Network/Adventure/AdventureService.swift, Offroad-iOS/Offroad-iOS/Network/Base/BaseService.swift, Offroad-iOS/Offroad-iOS/Network/Base/ErrorResponseDTO.swift, Offroad-iOS/Offroad-iOS/Network/Base/NetworkResult.swift, Offroad-iOS/Offroad-iOS/Network/Character/CharacterService.swift, Offroad-iOS/Offroad-iOS/Network/CharacterChat/CharacterChatService.swift, Offroad-iOS/Offroad-iOS/Network/Coupon/CouponService.swift, Offroad-iOS/Offroad-iOS/Network/Notice/NoticeService.swift, Offroad-iOS/Offroad-iOS/Network/Place/PlaceService.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/ViewControllers/CharacterChatLogViewController.swift
- #365 
현재 서버 API 사용 시 200대 상태 코드, 즉 성공 시에 데이터를 받아오도록 구현되어 있습니다.
우리 프로젝트의 서버 통신 코드 중 상태 코드에 따라 특정 종류의 에러로 구분해주는 `fetchNetworkResult(statusCode:data:)` 메서드에서 이를 담당하는데, 이때 성공 시 Response Body 의 타입을 제네릭타입으로 decode하여 서버로부터 데이터를 가져올 수 있습니다. 
그러나 현재 코드는 400대, 500대 상태 코드에서는 Response Body를 받아올 수 없다는 한계점이 있습니다. 
현재 서버에서는 400대, 500대 상태에 대해서도 응답 데이터(Body)를 포함하며, 필요 시 이 때의 `message`와 `customErrorCode`를 사용해야 하는 경우도 발생합니다. 
따라서 이를 받아올 수 있도록 하기 위해 코드를 수정하였습니다.
현재 우리 코드에는 ErrorResponseDTO 타입이 정의되어있으며, 200대 에러에서 연관값으로 제네릭 타입의 값을 반환하는 것처럼, 
400대, 500대 에러의 경우 ErrorResponseDTO 타입을 반환하도록 구현하였습니다. 
사용법은 다음과 같습니다. 채팅 로그를 받아오는 데이터를 예로 들겠습니다. 
서버 통신  API 메서드를 호출 후 콜백 함수의 매개변수가 `.success`나 `.decodeErr` 가 아닌 케이스일 경우에는 연관값으로 `ErrorResponsDTO` 타입의 값을 받아오게 됩니다. 
``` swift 
private func …
```
=> [Fix] #365 - ErrorResponseDTO 사용할 수 있도록 개선

Offroad-iOS/Offroad-iOS/Network/Base/MoyaPlugin.swift, Offroad-iOS/Offroad-iOS/Presentation/Login/ViewController/LoginViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/MarketingConsent/ViewController/MarketingConsentViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Onboarding/ViewController/TermsConsentPopupViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Onboarding/ViewController/TermsConsentViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Splash/ViewController/SplashViewController.swift
- #367
- 온보딩 도중 이탈 시, 무조건 스플래시 이후 로그인뷰로 이동
- 현재 서버 API가 수정되지 않아 닉네임을 설정한 이후에 이탈하고, 이전에 설정했던 닉네임을 다시 입력하면 중복된 닉네임으로 뜨는 버그가 있습니다! 서버 수정 후 반영되면 해결될 문제로 보여집니다.
- 온보딩 약관 동의 뷰 팝업 로딩 시점 변경
- 마케팅 수신 동의 시 토스트 구현
- 따로 디자인이 지정되어있지 않아, 기존에 구현되어있던 토스트를 사용하였습니다.
|온보딩 이탈 시 재로그인|온보딩 팝업 로딩|
|<img src = "https://github.com/user-attachments/assets/5a686efe-835b-4236-afc4-213eefcc7e64" width ="250">|<img src = "https://github.com/user-attachments/assets/4ac31f02-b1b7-492e-b227-b4acc2ec31e4" width ="250">|
|마케팅 수신 동의 토스트((온보딩 뷰)|마케팅 수신 동의 토스트(설정 뷰)|
|<img src = "https://github.com/user-attachments/assets/9cc150a2-1276-4033-89b7-1f58b5552638" width ="250">|<img src = "https://github.com/user-attachments/assets/ad83fb1a-e251-4e61-969a-e61e43debdaf" width ="250">|
- Resolved: …
=> [Fix] #367 - 온보딩 약관동의 뷰 개선

Offroad-iOS/Offroad-iOS/Network/CharacterChat/CharacterChatAPI.swift, Offroad-iOS/Offroad-iOS/Network/CharacterChat/CharacterChatService.swift, Offroad-iOS/Offroad-iOS/Network/CharacterChat/DTO/Response/CharacterChatPostResponseDTO.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/ViewControllers/CharacterChatLogViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/ViewModel/CharacterChatLogViewModel.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/Views/CharacterChatLogView.swift
- #370 
채팅 로그 뷰의 무한스크롤을 구현하였습니다. 
- 추가적인 채팅 내역(초깃값 포함)을 요청하는 메서드는
`updateChatLogDataSource(characterId:limit:cursor:completion:)` 입니다. 
처음에는 28개의 채팅을 불러오고, 이후부터는 한 번에 14개씩 불러오게 됩니다. 
- 서버에 요청하여 받아온 추가적인 채팅 내역을 바탕으로 컬렉션뷰를 업데이트하는 메서드는 `expandChatLogCollectionView()` 입니다. 이 메서드는 변경된 dataSource를 바탕으로 추가된 `Section`과 `Item`들을 계산하여 컬렉션뷰에 추가합니다. 
- 무한스크롤을 통해서 모든 채팅 내역을 불러올 경우 (서버의 응답 값이 비어있을 경우) 더 이상 서버에 요청하지 않도록 구현하였습니다.
(`didGetAllChatLog` 플래그의 역할)
- 무한스크롤로 인해 추가적인 데이터를 받아올 때 스크롤이 부자연스럽게 잠깐 끊기는 현상이 있습니다. 참고해주세요
(이걸 해결해보려고 했는데, 도저히 지금 상황에서는 시간 내에 못할 것 같아서 일단 후순위로 미뤄둔 상태입니다.)
- 현재 채팅 로그에서 이전 채팅 내역을 요청하는 조건은 scrollView의 `contentOffset`입니다.
추후 UX 개선 시 해당 조건이 추가되거나 변경될 수 있습니다.
- 현재 무한 스크롤 기능은 구현되어있으나, 로딩 로티는 적용되지 않은 상황입니다. 
이전 작업에서 제가 `UIScrollView`를 확장하여 로딩 로티를 표시하는 메서드를 구현한 적이 있는데, 
해당 메서드의 개선이 …
=> [Feat] #370 - 채팅 로그 뷰 무한스크롤 구현

Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewController/CharacterDetailViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewModel/CharacterDetailViewModel.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/CouponDetailViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/PlaceList/ViewControllers/PlaceListViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/QuestMapViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewModel/QuestMapViewModel.swift
- #376 
인터넷 연결이 끊겨 서버로부터 아무런 데이터도 받지 못하는 경우, 네트워크 에러 관련 토스트를 띄워야 합니다. 
이때, MoyaPlugin에서 해당 케이스에서 토스트를 띄우도록 구현함에 따라, 
제가 작업한 뷰컨트롤러들에서 서버 통신 실패 시 토스트를 띄우는 메서드를 지움으로써 해당 메서드가 중복으로 호출되는 것을 방지하였습니다. 
관련 뷰 혹은 서버 통신은 다음과 같습니다. 
- 지도에서 장소 목록 조회, 장소 목록 뷰
- 탐험 (위치)인증
- 캐릭터 상세 뷰
- 캐릭터 상세 뷰
- 대표 캐릭터로 선택하는 API
|뷰|설명|
- Resolved: #376
=> [Chore] #376 - 바뀐 MoyaPlugin 대응

Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj, Offroad-iOS/Offroad-iOS/Network/CharacterChat/CharacterChatAPI.swift, Offroad-iOS/Offroad-iOS/Network/CharacterChat/CharacterChatService.swift, Offroad-iOS/Offroad-iOS/Network/CharacterChat/DTO/Response/CharacterChatReadGetResponseDTO.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/ORBCharacterChatManager.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/ViewControllers/ORBCharacterChatViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/ViewControllers/CharacterChatLogViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Home/View/HomeView.swift, Offroad-iOS/Offroad-iOS/Presentation/Home/ViewController/HomeViewController.swift
- #372 
캐릭터 채팅 읽음 기능을 구현하였습니다. 
캐릭터로부터 선톡이 왔을 때 사용자가 채팅을 읽지 않으면 이를 사용자에게 알려주어야 합니다.
또한 사용자가 최신 채팅을 읽으면 읽었음을 확인하여 서버에 알려주어야 합니다.
추가된 주요 기능들은 다음과 같습니다. 
- 홈 화면의 메시지 버튼(채팅 버튼) 옆의 빨간 점
홈 화면에 있는 메시지 버튼(채팅 버튼) 옆에 뜨는 빨간 점은 캐릭터의 가장 최근 채팅을 읽지 않은 상태인지 여부를 알려줍니다. 
즉, 현재 홈 화면에 뜨는 캐릭터(==대표 캐릭터)의 최근 메시지 읽음 여부를 확인해야 하며, `~/api/chats/read(PATCH)`API를 통해 확인합니다.
현재는 채팅 읽음 여부를 `viewWillAppear` 에서 확인하고 있는데요, 호출 위치나 방식은 추후 개선될 필요가 있어 보입니다. (캐릭터 선톡이 올 때 최신 채팅 읽음 여부를 업데이트해야 할 듯 합니다.)
홈 화면의 메시지 버튼 옆에 빨간 점이 있을 경우, 메시지 버튼(채팅 버튼)을 누르면 키보드가 올라오는것 뿐만 아니라 가장 최근의 메시지가 같이 보이게 됩니다. 
- 채팅 읽음 여부 확인
캐릭터의 최신 채팅을 읽었는지 여부를 확인하여 서버에 이를 알려야 합니다. 
현재('24.12.17 오후 12:05) 화면설계서 기준 캐릭터의 선톡 채팅의 읽음 기준은 다음과 같습니다.
1) 캐릭터 선톡이 푸시 알림으로 왔을 때 해당 알림을 탭하여 앱에 접속한 경우
2) 앱 접속 후 플레이 중 캐릭터 선톡이 상단에 띄워졌을 때 답장하기를 탭하여 키보드가 올라온 경우
3) 앱 접속 후 플레이 중 캐릭터 …
=> [Feat] #372 - 캐릭터 채팅 읽음 여부 

Offroad-iOS/Offroad-iOS/Application/AppDelegate.swift, Offroad-iOS/Offroad-iOS/Global/Components/Overlay/Alert/ORBAlertController.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/ORBCharacterChatManager.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/ViewControllers/ORBCharacterChatViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/Views/ORBCharacterChatBox.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/Views/ORBCharacterChatView.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/ViewControllers/CharacterChatLogViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Home/ViewController/HomeViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/CouponDetailViewController.swift
- #385 
단어가 헷갈릴 수도 있어서, 본 PR에서는 캐릭터 선톡 시에 위에서 내려오는 토스트?를 "캐릭터 채팅 박스" 라는 단어로 통일하겠습니다.
- 캐릭터 채팅 창 터치 피드백 구현, 제스처 개선
- 현재 캐릭터 채팅 창에서 답장하기 버튼이 있는 경우에 한해서 채팅을 탭 하면 채팅 로그로 이동하도록 되어있는데,
답장하기 버튼이 없는 경우에도 탭 시 채팅 로그로 이동하도록 구현
- 캐릭터 채팅 박스에 뜨는 메시지 줄 수 제한
- 캐릭터 채팅 박스 chevron 버튼 탭 영역 확장
- 처음 한 번 채팅 박스 혹은 채팅 입력창이 뜰 때 이상하게 나타났다 사라지는 문제 해결
(초깃값을 숨김 처리하였으며, 캐릭터 채팅 박스가 보이거나 채팅 입력창이 보일 때 `isHidden`에 `false`를 할당하였습니다.)
- 채팅 로그뷰를 보고 있을 때 선톡이 오는 경우 캐릭터 채팅 박스가 뜨는 대신 채팅 말풍선이 추가되도록 구현
- 홈 화면에서 최근 채팅 읽음 여부를 나타내는 빨간 점? 구현
- ORBAlertController의 textField로 인해 키보드 올라왔을 때 캐릭터 선톡이 오면 이상하게 동작하는 현상 해결
- 채팅 입력창 흰색 테두리 주변으로 그림자 추가
쿠폰 입력 시 ORBAlertController의 배경색과 채팅 입력 창의 배경색이 같아 경계가 보이지 않는 문제가 있어 그림자를 추가하였습니다. 
- 캐릭터 선톡 3초 뒤에 사라지도록 구현
조건부임. 답장하기 버튼을 누르거나, 사용자가 메시지를 보내고 캐릭터로부터 온 답장의 경우는 자동으로 사라지지 않음. …
=> [Fix] #385 - 캐릭터 채팅 동작 개선

Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/ViewControllers/ORBCharacterChatViewController.swift
- #397
현재 캐릭터 선톡이 오면 채팅 박스가 3초 뒤에 사라지는데, 사용자가 터치에 개입할 경우 3초 카운트를 초기화하도록 구현한 상태입니다.
이때 
- 채팅 박스 확장을 위한 chevron버튼을 눌렀을 경우
- 사용자가 채팅 박스를 press만 하고 있는 경우
에는 3초 카운트가 일시정지되지 않아서, 사용자가 의도하지 않은 상황에 캐릭터 채팅 박스가 사라지는 현상이 발생합니다. 
위의 경우에도 3초 카운트를 초기화하는 로직을 추가하였습니다. 
|변경 전|변경 후|
|:----:|:---:|
|    <img src="https://github.com/user-attachments/assets/63d4c991-8f3b-4137-83e3-10c72c29696d" width=200>    |   <img src="https://github.com/user-attachments/assets/f32ea66a-cbcc-4f46-9f02-8cf6df977653" width=200>  |
- Resolved: #397
=> [Chore] #397 - 캐릭터 선톡 시 3초 후 사라지는 로직 개선

Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
- #404 
형식 오류가 생겼을 때 error borderColor가 적용이 안되는 문제를 해결했습니다. 리팩토링 이후 따로 UI 처리를 해줘야 했는데, `self.view.endEditing(true)` 이후에 `primary(.errorNew)`를 적용하여 textfield 포커스가 해제되었을 때도 에러 색상이 유지되도록 했습니다. 
텍스트 필드 focus 이벤트 바인딩하는 부분에서 기존에 `self.whetherDuplicate`의 경우만 분기 처리하여 형식 오류일 때의 에러 색상이 적용이 안되는 문제가 생겼는데, 형식 오류일 때의 분기 처리도 추가하여 해결했습니다.
|뷰|설명|
- Resolved: #404
=> [Chore] #404 - 닉네임 뷰 에러처리 수정사항 적용

Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/CouponListViewController.swift
- #416 
쿠폰 사용 후 목록이 비었을 때 cell의 갯수가 최신화되지 않는 문제가 발견되었습니다. 
쿠폰 사용 후 쿠폰 목록 뷰를 업데이트하게 되는데, 이 과정에서 받아온 쿠폰 목록의 수가 0인 경우, 엠티 케이스가 되어 위 이미지처럼 노바 캐릭터를 띄우도록 되어있습니다. 이때, 캐릭터를 띄우는 작업만 하고, 컬렉션뷰의 data를 reload하는 과정이 생략되어 위와 같은 문제가 발생합니다. 
이를 수정하기 위해 collectionView에서 reloadData() 메서드를 호출하는 코드를 추가하였습니다. 
제가 쿠폰이 없어, 잘 동작하는지 확인은 하지 못했으나, 잘 동작할 것으로 예상합니다. 
혹시 쿠폰이 있어 테스트가 가능하신 분은 잘 동작하는지 확인 부탁드립니다. 
|뷰|설명|
- Resolved: #416
=> [Fix] #416 - 쿠폰 사용 후 목록이 비었을 때 cell의 갯수가 최신화되지 않는 문제 해결

Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/Views/CharacterChatLogView.swift
- #428 
채팅 로그 뷰의 '채팅하기' 버튼이 줄바꿈되어 보이는 문제 해결하였습니다.
정확한 원인은 파악되지 않았으나, 
기기의 설정에서 텍스트 크기를 변경할 시 채팅 로그 뷰의 '채팅하기' 버튼의 텍스트 크기도 이에 맞추어 변경되는 것을 확인했으며, 
이로 인해 줄바꿈이 되는 것으로 파악됩니다. 
이는 해당 버튼에서 폰트를 별도로 설정해주지 않았기 때문이므로, 해당 버튼에 폰트를 설정해 주었습니다. 
|문제 상황|해결|
|  <img src="https://github.com/user-attachments/assets/e1272ab7-f1d8-4a61-8b34-9791633d1cfb" width=300>  |  <img src="https://github.com/user-attachments/assets/16e22622-f402-4e31-9844-e062f1bc9736" width=300>  |
- Resolved: #428
=> [Chore] #428 - 채팅 로그 뷰의 '채팅하기' 버튼이 줄바꿈되어 보이는 문제 해결

Offroad-iOS/Offroad-iOS/Global/Literals/StringLiterals.swift
- #435 
위치 관련 안내 문구 중 일부를 수정하였습니다. 
변경된 내용은 다음과 같습니다. 
- "위치 기능이 비활성화되어 있습니다.\n탐험을 인증하기 위해서는 위치 기능을 활성화해 주세요."
-> "모험가님의 위치를 찾을 수 없어요.\n탐험을 위해서 위치 기능을 활성화해주세요."
- "\"정확한 위치\" 기능이 꺼져 있습니다. 탐험을 위해서는 정확한 위치 접근을 허용해 주세요."
-> "모험가님의 정확한 위치를 찾을 수 없어요.\n탐험을 위해서 정확한 위치 접근 권한을 허용해주세요."
|뷰|설명|
- Resolved: #435
=> [Chore] #435 - 위치 관련 안내 문구 수정

Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/Views/ORBCharacterChatWindow.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/View/CharacterDetailView.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewController/CharacterDetailViewController.swift
- #441 
채팅 로그의 뷰가 부자연스럽게 나타나는 현상을 일부 해결하였습니다. 
현재 채팅 로그에 진입할 때, 배경에 투명도를 주어 이전 화면의 블러가 표시되도록 구현한 상태입니다.
그런데, `UINavigationController`의 기본 동작은 push되면서 이전 화면이 왼쪽으로 슬라이딩되기 때문에
이전 화면을 캡처한 후 이를 채팅 로그의 배경에 넣는 방식으로 구현한 상태인데요,
채팅 로그 뷰가 push되는 순간에 이전 화면이 스크롤되는 경우, 캡처하는 시점의 화면과 다른 화면이 채팅 로그의 배경으로 사용되어 어색한 부분이 발생합니다.
채팅 로그가 push되는 시점에 이전 화면의 스크롤을 제한하여 조금 더 자연스러운 UI를 구현하였습니다. 
아직 일부 상황에서는 여전히 부자연스럽게 동작하나, 사용자 경험에 크게 영향을 미치는 부분이 아니라고 판단하여 간단한 변경점만을 적용하였습니다. 
| 전 | 후 |
|    <img src="https://github.com/user-attachments/assets/8d93b8f6-1804-45f4-9e74-e24504e7926d" width=300>   |   <img src="https://github.com/user-attachments/assets/db574848-cb30-4759-a12b-64f8a3275c6e" width=300>  |
- Resolved: #441
=> [Fix] #441 - 채팅 로그 뷰의 배경이 부자연스럽게 나타나는 현상

Offroad-iOS/Offroad-iOS/Presentation/Login/View/LoginView.swift
- #444 
숨김처리되어있던 카카오로 로그인 버튼을 다시 보이도록 수정하였습니다. 
|뷰|설명|
- Resolved: #444
=> [Feat/#444] 카카오 소셜 로그인버튼 숨김 해제

Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj, Offroad-iOS/Offroad-iOS/Application/SceneDelegate.swift, Offroad-iOS/Offroad-iOS/Global/Components/Overlay/ConsoleLog/ConsoleLogManager.swift, Offroad-iOS/Offroad-iOS/Global/Components/Overlay/ConsoleLog/ConsoleLogView.swift, Offroad-iOS/Offroad-iOS/Global/Components/Overlay/ConsoleLog/ConsoleLogViewController.swift, Offroad-iOS/Offroad-iOS/Global/Components/Overlay/ConsoleLog/ConsoleLogWindow.swift, Offroad-iOS/Offroad-iOS/Global/Components/Overlay/ConsoleLog/PrintLogInDevApp.swift, Offroad-iOS/Offroad-iOS/Network/Base/MoyaPlugin.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/ViewControllers/ORBCharacterChatViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/ViewControllers/CharacterChatLogViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/CouponDetailViewController.swift
- #453 
개발용 앱에서 로그를 확인할 수 있도록 구현하였습니다. 
엑스코드 콘솔이 있어야만 확인할 수 있는 문구들을 개발용 앱에서도 볼 수 있으면 좋을 것 같아 이러한 기능을 만들어 보았습니다. 
- 특정 위치에 로그가 고정되어있기에는 로그가 길 경우, UI를 가리게 될 것 같아 플로팅 버튼을 만들어 이 버튼을 눌렀을 때 로그가 보이거나 숨겨질 수 있도록 구현하였습니다.
- 로그가 펼쳐진 후에도 로그 뷰의 세로 위치를 조정할 수 있도록 하였습니다. 
- `printLog(_:)` 메서드를 이용하여 앱 내에서 원하는 로그를 띄울 수 있습니다.
OS에서 출력하는 로그는표시하지 않고, 개발자가 원하는 내용만 표시할 수 있습니다.
현재는 `MoyaPlugin`에서 출력하는 내용과, 제가 개발했던 코드의 일부에서 `printLog(_:)`를 사용하였습니다. 
- `printLog(_:)`는 호출할 때마다 로그가 누적되어 표현되는 것이 아니라 새 로그가 표시됩니다. 
(로그가 누적되면 버벅거리고, 메모리가 너무 늘어날 것 같아 새로고침되도록 하였습니다. 자세한 로그를 확인하고자 한다면 Xcode를 참고해 주세요.))
- ### 지금 생각해보니, `Console` 이라는 단어를 뺴는 것이 더 적절해 보이기도 합니다. `LogPrinter`와 같은 이름이 더 직관적인것 같네요.
콘솔 자체는 명령어를 입력받을 수 있어야 하는데, 여기서 구현된 것은 콘솔이라기보다는 그저 로그를 출력해주는 창 정도에 더 가깝기 때문입니다. 
이에 관한 파트원들의 의견을 받습니다. 
(2월 4일 자정까지 리뷰가 없을 경우, 콘솔이라는 …
=> [Feat] #453 - 개발용 앱에서 로그 확인 기능 구현

Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj, Offroad-iOS/Offroad-iOS/Global/Components/Overlay/Alert/ORBAlertController.swift, Offroad-iOS/Offroad-iOS/Global/Components/Overlay/LogPrinter/LogPrinterViewController.swift, Offroad-iOS/Offroad-iOS/Global/Components/Overlay/LogPrinter/LogPrinterWindow.swift, Offroad-iOS/Offroad-iOS/Global/Literals/StringLiterals.swift, Offroad-iOS/Offroad-iOS/Presentation/QuestMap/PlaceInfoTooltip/PlaceInfoTooltipHelper.swift, Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/ORBMapViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/QuestMap/Views/ORBMapHelper.swift, Offroad-iOS/Offroad-iOS/Presentation/QuestMap/Views/ORBMapView.swift
- #461 
- #### `ORBMapHelper`와 `PlaceInfoTooltipHelper` 추가
기존 코드는 `ORBMapViewController`에서 너무 많은 일을 담당하고 있다고 판단하였습니다. 
기존 `ORBMapViewController`는 터치 이벤트를 처리하고, mapView(네이버 지도)의 delegate, locationManager의 delegate 등의 역할을 맡았는데요, 특히, 툴팁과 지도에 부드러운 애니메이션을 적용하기 위한 함수들이 `ViewController`에서 모두 구현되어 있었습니다.
이로 인해 `ViewController`가 너무 커졌다고 생각했습니다. 
그렇다고 이 애니메이션 코드를 viewModel로 옮기기에는 애매한 게, 애니메이션 코드는 model과는 무관하게 그저 뷰의 UI가 변하는 것만 구현되어있어서, viewModel에서 구현하는 것도 알맞은 위치가 아니라고 생각하였고, view에도 옮겨보았으나(`ORMMapView`) 이 또한 view의 크기를 지나치게 키운다고 생각하여 결국 해당 함수의 역할을 별도의 다른 객체에 분리하는 것이 바람직하다고 판단하였습니다.
이를 위해 `ORBMapHelper`와 `PlaceInfoTooltipHelper` 두 타입을 추가헀습니다. 
`ORBMapHelper`의 역할은 지도를 움직이는 애니메이션을 구현하는 것 입니다.
`PlaceInfoTooltipHelper`의 역할은 지도에 보일 tooltip이 생기고 사라질 때의 애니메이션을 구현하는 것 입니다. 
뷰컨트롤러에서 두 helper를 생성하여, 지도/툴팁 의 …
=> [Refactor] #461 - 지도 뷰 코드 개선

Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj, Offroad-iOS/Offroad-iOS/Global/Components/Chat/ChatTextDisplay/ChatTextDisplayView.swift, Offroad-iOS/Offroad-iOS/Global/Components/Chat/ChatTextInput/ChatTextInputView.swift, Offroad-iOS/Offroad-iOS/Global/Components/Overlay/Alert/ORBAlertController.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/ORBCharacterChatManager.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/ViewControllers/ORBCharacterChatViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/Views/ORBCharacterChatView.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/Views/ORBCharacterChatWindow.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/ViewControllers/CharacterChatLogViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/Views/CharacterChatLogView.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/CouponDetailViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/TabBar/ViewControllers/OffroadTabBarController.swift
- #463 
기존 코드에서 채팅 시(홈 화면에서 채팅, 채팅 로그 둘 다) 우리 앱이 갖는 중요 문제점이 있다고 느꼈습니다. 
- 첫 번째는 사용자가 채팅하고자 해도 키보드가 올라오지 않을 때(아이폰 미러링이나, 아이패드에서 애플펜슬을 이용한 입력 등) 채팅 입력창이 화면에 나타나지 않는다는 문제였습니다.
|홈 화면에서 입력창이 생기지 않는 상황|채팅 로그에서 입력창이 뜨지 않는 상황|
|   <img src="https://github.com/user-attachments/assets/cf5bae84-c442-442a-baa5-c8a3f8cdf2b8" width=150>   |  <img src="https://github.com/user-attachments/assets/a97f962e-5e42-49b7-a44a-f7777b009af8" width=150>  |
- 두 번째는 외부적으로 드러나는 문제는 아니지만, 채팅 입력창의 코드가 불필요하게 복잡하고 반복된다는 점이었습니다. 
특히 채팅창에 글씨가 입력될 때나 전송될 때 적용되는 애니메이션 코드는 거의 하드코딩을 하다시피하여 코드가 불필요하게 복잡해지고 반복된다고 느꼈습니다. 
특히 두번째 문제가 근본적으로 해결이 필요하다고 느꼈습니다. 왜냐하면 현재 코드의 유지보수도 어렵고 3차 스프린트에서 추가될 '오브의 추천소' 기능에서도 비슷한 UI가 구현될 가능성이 높기 때문입니다. (그러면 또 비슷한 코드가 반복되겠지요.) 그리고 두 번째 문제를 해결하면 첫 번째 문제의 해결도 자연스레 따라올 것이라 생각했습니다. 결과부터 …
=> [Refactor] #463 - 채팅 입력창 기능 분리

Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj, Offroad-iOS/Offroad-iOS/Global/Components/Overlay/Loading/ScrollLoadingCollectionView.swift, Offroad-iOS/Offroad-iOS/Presentation/PlaceList/ViewControllers/PlaceListCollectionViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/PlaceList/ViewControllers/PlaceListViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/PlaceList/Views/PlaceListCollectionView.swift, Offroad-iOS/Offroad-iOS/Presentation/PlaceList/Views/PlaceListView.swift
- #466 
장소 목록 뷰에서 각 컬렉션뷰의 역할을 분리하였습니다.
현재 `PlaceListViewController`에서는 한 개의 pageViewController와 두 개의 (collectionView를 띄우는) viewController 모두를 관리하고 있습니다. 
이때 pageViewController나 collectionView의 dataSource 및 delegate를 모두 한 곳에서 도맡아 관리하기 때문에 코드가 복잡해진다고 생각했습니다.
장소 목록 뷰의 뷰컨트롤러(PlaceListViewController)에서는 pageViewController만을 관리하고, 이 pageViewController에 들어가는 뷰컨트롤러 타입은 별도로 만들어서 따로 관리하는 게 더 효율적이라고 판단하였습니다.
이를 위해 `PlaceListCollectionViewController`를 대폭 수정하였고, `PlaceListCollectionView` 타입을 추가하였습니다.
- 새로 추가된 `PlaceListCollectionView`는 장소 목록 뷰에서 보여줄 collectionView 자체에 해당합니다. 이 collectionView의 레이아웃과 기본적인 디자인을 이 타입에서 구현합니다.
- `PlaceListCollectionViewController`의 타입은 원래 `UIViewController`였지만, `UICollectionViewController` 타입으로 변경하였습니다.
이로 인해 `PlaceListCollectionViewController`는 `PlaceListCollectionView`의 …
=> [Refactor] #466 - 장소 목록 뷰에서 컬렉션 뷰 기능 분리

Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/ViewControllers/CharacterChatLogViewController.swift
- #470 
채팅 로그에서 채팅 내역이 없을 시 '채팅하기' 버튼이 보이지 않는 문제가 발견되어, 이를 해결하였습니다.
또한, 기존에는 채팅하기 버튼을 누르면 채팅하기 버튼이 숨겨졌는데, 
숨겨질 경우, 채팅 내용이 없으면 버튼이 다시 나타나지 않는 문제가 발견되어 채팅 버튼을 눌러도 숨겨지지 않도록 하였습니다.
|뷰|설명|
|     <img src="https://github.com/user-attachments/assets/00daa4d7-b7ec-429e-b1ae-bb2961d2538e" width=200>   |  <img src="https://github.com/user-attachments/assets/d711f171-71a2-4165-9e2b-219593039cad" width=200>   |
- Resolved: #470
=> [Fix] #470 - 빈 채팅 로그에서 채팅하기 버튼이 보이지 않는 문제 해결

Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj, Offroad-iOS/Offroad-iOS/Global/Components/Overlay/Alert/AlertView/ORBAlertViewMessageOnly.swift, Offroad-iOS/Offroad-iOS/Global/Components/Overlay/Alert/AlertView/ORBAlertViewNormal.swift, Offroad-iOS/Offroad-iOS/Global/Components/Overlay/Alert/ORBAlertBackgroundView.swift, Offroad-iOS/Offroad-iOS/Global/Components/Overlay/Alert/ORBAlertType.swift, Offroad-iOS/Offroad-iOS/Global/Components/Overlay/Alert/Protocols/ORBAlertViewBaseUI.swift, Offroad-iOS/Offroad-iOS/Global/Literals/StringLiterals.swift, Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/btn_diary.imageset/Contents.json, Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/btn_diary.imageset/btn_diary.svg, Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Setting/img_clock.imageset/Contents.json, Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Setting/img_clock.imageset/img_clock.svg, Offroad-iOS/Offroad-iOS/Presentation/MyPage/Component/MyPageScrollView.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/DiaryTime/Enum/TimePeriod.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/DiaryTime/View/DiaryTimeView.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/DiaryTime/ViewController/DiaryTimeViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/Model/SettingBaseModel.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/ViewController/SettingViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/View/MyPageView.swift
- #465
- 일기 시간 설정 뷰의 UI를 구현했습니다.
- 마이 페이지에서 일기 버튼이 보이도록 추가했습니다.(일기 시간 설정 뷰와는 무관합니다.)
`MyPageCustomButton`이 `ShrinkableButton`을 상속하도록 변경하면서, 마이 페이지 내부에서 스크롤을 할 때 버튼의 바로 위에서 스크롤을 할 시 원활하게 동작하지 않는 문제를 해결하기 위해서 `MyPageScrollView`를 생성하였습니다.
`touchesShouldCancel`를 조작하여 UIButton에서 true를 반환하도록 설정해준 코드만 추가해주었습니다.
```
final class MyPageScrollView: UIScrollView {
override func touchesShouldCancel(in view: UIView) -> Bool {
if view is UIButton {
return true
}
return super.touchesShouldCancel(in: view)
}
}
```
- ORBAlertController 관련 코드를 일부 수정했습니다.(채널톡 사전 공유한 부분)
|일기 시간 뷰|마이 페이지|
|<img src = "https://github.com/user-attachments/assets/3df7f61d-88d9-4b87-bc87-1e1d9f1c21ea" width ="250">|<img src = "https://github.com/user-attachments/assets/e4b22ec9-e130-48aa-a1d5-489c9459fd13" width …
=> [Feat] #465 - 일기 시간 뷰 UI 구현

Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj, Offroad-iOS/Offroad-iOS/Global/Amplitude/AmplitudeManager.swift
- #484 
- [AmplitudeManager.swift 파일을 배포용 타겟에서 제거하면서 발생하는 문제](https://desk.channel.io/z3vne/threads/groups/1_%EC%95%84%EC%9A%94-409118/67d282e7e552c44772e5/67d534279d06a651dd3e) 해결
AmplitudeManager.swift 파일을 개발용 타겟에만 한정하였더니, 이 객체를 활용하는 코드에서 에러가 발생하였습니다.
(trackEvent 메서드를 호출하는 곳)
배포용 타겟에 포함하되, Amplitude 기능 적용 범위를 개발용 타겟으로 한정하는 방법을 이용하여 문제를 해결하였습니다.
amplitude 변수를 옵셔널 타입으로 구현하여 개발용 타겟에서 컴파일될 경우 nil을 할당하였습니다.
AmplitudeManager 의 전체 코드는 다음과 같습니다.
``` swift
import Foundation
import AmplitudeSwift
/// Amplitude 객체를 보관하는 싱글톤 객체.
/// 이벤트를 트래킹하는 간단한 동작들 구현
public class AmplitudeManager {
//MARK: - Type Properties
static var shared = AmplitudeManager()
//MARK: - Properties
/// background에서 다음 시간 동안 아무런 앰플리튜드 이벤트가 발생하지 않을 경우 세션 종료. millisecond 단위이며, 10분으로 설정
private let minTimeBetweenSessionsMillis: …
```
=> [Fix] #484 - AmplitudeManager 동작 범위 수정

Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj, Offroad-iOS/Offroad-iOS/Presentation/Diary/Modal/MonthPickerModalView.swift, Offroad-iOS/Offroad-iOS/Presentation/Diary/MyDiaryManager/MyDiaryManager.swift, Offroad-iOS/Offroad-iOS/Presentation/Diary/View/DiaryView.swift, Offroad-iOS/Offroad-iOS/Presentation/Diary/ViewController/DiaryViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Diary/ViewController/MonthPickerModalViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Diary/ViewModel/DiaryViewModel.swift
- #477
일기 캘린더 pickerView를 구현했습니다.
- `MyDiaryManager`라는 싱글톤 객체를 생성하였으며 일기 기능에서 저장해야할 데이터나 전역적으로 관리할 로직을 담을 예정입니다.
- 현재 보여지는 캘린더 페이지와 PickerView의 선택된 연도/월 데이터를 일치시킬 수 있도록 RxSwift를 활용하여 바인딩했습니다.  
|iPhone SE|iPhone 16|
|<img src = "https://github.com/user-attachments/assets/27e67ada-bf75-46ce-ab8d-e1e3254ad367" width ="280">|<img src = "https://github.com/user-attachments/assets/65b31071-096c-4145-bd2d-5678a038215e" width ="280">|
- Resolved: #477
=> [Feat] #477 - 일기 캘린더 pickerView 구현

Offroad-iOS/Offroad-iOS/Application/AppDelegate.swift, Offroad-iOS/Offroad-iOS/Global/Literals/StringLiterals.swift, Offroad-iOS/Offroad-iOS/Presentation/Diary/MyDiaryManager/MyDiaryManager.swift, Offroad-iOS/Offroad-iOS/Presentation/Home/View/HomeView.swift, Offroad-iOS/Offroad-iOS/Presentation/Home/ViewController/HomeViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/MemoryLight/ViewModel/MemoryLightViewModel.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/Notice/NoticePost/ViewController/NoticePostViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/ORBMapViewController.swift
- #495
일기 fcm을 연결했습니다.
- fcm을 수신했을 때, 팝업 띄우고 최신 일기 확인 여부 UI 업데이트(일기 버튼 위 빨간 점)하도록 구현 
- 공지사항 외부링크 연결되지 않던 버그 해결
|앱 실행 중 fcm 수신(일기 바로 확인)|앱 실행 중 fcm 수신(일기 나중에 확인)|
|:------:|:------:|
|<img src = "https://github.com/user-attachments/assets/18b3a786-9988-4f9e-9f97-91fe8896d987" width ="280">|<img src = "https://github.com/user-attachments/assets/770beb99-7020-4bc6-86a0-66adb2681ba2" width ="280">|
|앱이 실행 중이지 않을 때 fcm 수신|공지사항 리다이렉션 에러 처리|
|:---:|:---:|
|<img src = "https://github.com/user-attachments/assets/9e965b85-f446-4fe4-a6de-72d6b7efe924" width ="280">|<img src = "https://github.com/user-attachments/assets/b091a384-3fee-435e-8a55-728c606be55e" width ="280">|
- Resolved: #495
=> [Network] #495 - 일기 fcm api 연결

Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewModel/ORBMapViewModel.swift
- #503 
오늘 새벽 작업 중에 배포용 앱 버전에서 위치와 무관하게 탐험이 인증되는 문제가 발생하여 긴급하게 조치 후 앱스토어에 버전을 업데이트하였습니다.
개인적으로 작업 후 앱스토어에 배포했으나, 깃허브에 공식적으로 변경 기록을 남기기 위해 별도로 PR 올립니다.
변경사항은 탐험 인증 시 현재 위치를 담을 DTO를 타겟별로 분기처리하는 것 위에는 없습니다. 
테스트를 위해 개발용 앱에서만 사용할 수 있는 다른 여러 기능들이 구현되면 좋을 것 같습니다.
추후 이런 기능들을 모아 앱의 설정 화면에서 수정할 수 있도록 구현할 예정입니다. 
|뷰|설명|
- Resolved: #503
=> [Fix] #503 - 위치 인증 타겟별 분기처리

Offroad-iOS/Offroad-iOS/Global/Components/ORBRecommendationGradient/ORBRecommendationBaseBackground.swift, Offroad-iOS/Offroad-iOS/Global/Components/ORBRecommendationGradient/ORBRecommendationGradientLayer.swift
- #525
기존 방법은 completionHandler 를 통해서 재귀적으로 호출하는 방법이었는데, 
이러한 방법으로 인해 무한하게 콜스택이 생성되고 성능에 문제가 되는 것을 발견했습니다.
Core Animation에서 무한하게 애니메이션을 구현하기 위해 `repeatCount = .infinity` 로 설정해 주었습니다.
그라데이션 애니메이션의 배경이 되는 그라데이션 레이어의 여유분을 30 -> 300 으로 증가시켰습니다.
(애니메이션을 구현하다보니 30으로는 부족한 것 같더라구요)
|뷰|설명|
- Resolved: #525
=> [Fix] #525 - 오브 그라데이션 애니메이션 성능 개선

Offroad-iOS/Offroad-iOS/Global/Components/Chat/ChatTextInput/ChatTextInputView.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/ViewControllers/ORBCharacterChatViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/Views/ORBCharacterChatView.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/ViewControllers/CharacterChatLogViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/Views/CharacterChatLogView.swift
- #527 
채팅 입력창의 레이아웃을 조정하였습니다.
기존 채팅 입력창은 textView의 `bottomAnchor`를 직접 `keyboardLayout`의 `topAnchor`과 연결하는 방식으로 레이아웃을 구성했는데요,
이렇게 하니까 키보드가 올라올 때 애니메이션이 적용이 되지 않거나 예상치 못하게 동작하는 경우가 발생하는 것 같았습니다.
또, 키보드가 올라올 때 `keyboardLayout` 대신 notification을 감지해서 조정하고 싶어도 제한사항이 있어서 이를 해결하고자 하였습니다.
수정한 chatInputView를 키보드 등에 연결하는 것은 chatInputView를 사용하는 곳(외부)에서 결정하게 됩니다.
이에 따라 현재 키보드 입력창을 사용하는 두 뷰(뷰컨트롤러)에서 바뀐 레이아웃에 맞게 조정하였습니다.
|뷰|설명|
- Resolved: #527
=> [Fix] #527 - 채팅 입력창 레이아웃 수정

Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/ViewControllers/CharacterChatLogViewController.swift
- #529 
채팅에 성공하면 로그를 업데이트하는 과정에서 의도한 것과 다른 방법으로 guard문이 사용되면서 guard문에서 코드가 조기 종료되는 문제가 발생했습니다.
기존 코드의 475-483번 줄 (`updateChatLog` 메서드 내에서)
``` swift
let dataSourceSectionCount = dataSource.snapshot().sectionIdentifiers.count
let dataSourceLastSectionItemCount: Int
// 여기서 `last`는 가장 오래된 section을 의미.(내림차순 정렬되어있기 때문) 의도한 대로의 코드대로라면 `first`로 적어야 함.
if let lastSection = dataSource.snapshot().sectionIdentifiers.last {
dataSourceLastSectionItemCount = dataSource.snapshot().itemIdentifiers(inSection: lastSection).count
} else {
dataSourceLastSectionItemCount = 0
}
// 만약 가장 처음 section(날짜)에서의 채팅이 하나뿐이면 (오브에게 선톡이 오고 답장을 하지 않은 경우) guard문에서 조건을 만족하지 못해 조기 종료됨.
guard dataSourceSectionCount > 0, dataSourceLastSectionItemCount > 1 else { return }
```
이를 해결하기 위해 불필요한 코드를 제거하고, `updateChatLog` 메서드를 전면적으로 …
=> [Fix] #529 - 채팅 말풍선 로딩이 끝나지 않는 문제 해결, 에러 추가

Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj, Offroad-iOS/Offroad-iOS/Network/Base/NetworkService.swift, Offroad-iOS/Offroad-iOS/Network/MinimumSupportedVersion/DTO/MinimumSupportedVersionResponseDTO.swift, Offroad-iOS/Offroad-iOS/Network/MinimumSupportedVersion/MinimumSupportedVersionAPI.swift, Offroad-iOS/Offroad-iOS/Network/MinimumSupportedVersion/MinimumSupportedVersionService.swift, Offroad-iOS/Offroad-iOS/Presentation/Splash/ViewController/SplashViewController.swift
- #437 
오브에서 정한 최소 지원 버전보다 앱의 버전이 낮을 경우 앱스토어로 이동하여 앱을 업데이트하도록 유도하는 기능을 구현했습니다.
`SplashViewController`에서 구현했으며,
현재 버전이 최소 지원 버전보다 낮을 경우 앱스토어로 리다이렉션하는 팝업을 띄우고 로그인을 진행하지 않습니다.
현재 버전이 최소 지원 버전 이상인 경우 사용자에게 별다른 안내 없이 로그인을 진행합니다.
- 코드를 깔끔하게 적기 위해 기존 `SplashViewController`의 `viewDidAppear` 메서드 안에서 구현되어있는 로그인 로직을 `processToLogIn()` 이라는 메서드로 감쌌습니다.
- `SplashViewController`에서 앱 버전을 체크하고 업데이트를 유도하는 메서드들만을 별도 `extension` 으로 감싸서 관리하였습니다.
* 현재 최소 지원 버전 정보을 요청하는 서버 API는 은 개발 서버에서만 동작하므로, 개발용 앱에서만 동작하도록 구현되어있습니다. 참고 바랍니다.
최소 지원 버전을 서버에 요청하는 코드를 구현하면서 `async/await` 를 적용해 보았습니다.
우리 팀에 `Swift Concurrency`를 도입한 적이 없어서 많이 낯설 수도 있을 것 같아, 최소한의 기능으로만 구현해 보았습니다. 아마 조금만 검색하시거나 `chatGPT` 등에 물어보시기만 해도 코드를 읽는데 큰 어려움은 없을 것이라 생각합니다. 그럼에도 불구하고 모르거나 헷갈리는 점이 있으면 물어봐 주세요! 저도 아직 공부중이라 같이 알아나가면 좋을 것 같습니다.
추후 여유로울 때 간단한 비동기 …
=> [Feat] #437 - 앱 업데이트 유도 기능 구현

Offroad-iOS/Offroad-iOS/Presentation/ORBRecommendation/chat/Views/ORBRecommendationChatView.swift, Offroad-iOS/Offroad-iOS/Presentation/ORBRecommendation/order/ORBRecommendationOrderView.swift
- #533 
다음 변화점들만을 포함합니다.
- 오브의 추천 주문서 장소 설명 공백 값을 무시하도록(스페이스만 있을 때에는 값을 입력하지 않은 것으로 간주)
- 오브의 추천 채팅 스크롤 인디케이터 색 설정(라이트/다크 모드 무관하게 모두 다크모드가 되도록)
|뷰|설명|
- Resolved: #533
=> [Chore] #533 - 사소한 코드 변화

Offroad-iOS/Offroad-iOS/Presentation/Login/AuthManager/TokenIntercepter.swift
- #538 
여러 대의 기기에서 로그인했을 때, 그 중 한 기기에서 회원 탈퇴를 진행하면 다른 앱에서 로그인이 진행되지 않는 문제가 발견되었습니다.
다른 기기에서 로그인 후 회원을 탈퇴하면 탈퇴한 기기가 아닌 다른 기기에는 여전히 `refreshToken` 값이 남아있는데요,
서버의 DB에는 이 `refreshToken`에 해당하는 계정이 사라지면서
`HTTP` 상태 코드로 `401`이 아니라 `404`가 반환됩니다. 
> 응답값: `{"message":"해당 ID의 유저가 존재하지 않습니다.","customErrorCode":"NOT_EXISTS_MEMBER"}`
현재 `TokenInterceptor`에는 401(`Unauthorized`)에 대한 대응은 되어있으나, 404일때의 분기처리가 되어있지 않아서 스플래시 화면에서 앱이 더 이상 진행하지 않고 멈춰있는 것처럼 보입니다.
HTTP 상태 코드로 404가 반환될 경우 401에서와 마찬가지로 로그인 화면으로 이동하도록 유도하였습니다.
|뷰|설명|
- Resolved: #538
=> [Fix] #538 - 다른 기기에서 회원 탈퇴한 경우, 스플래시 화면에서 다음으로 진행되지 않는 문제 해결

Offroad-iOS/Offroad-iOS/Presentation/PlaceList/Views/PlaceListView.swift
- #554 
장소 목록 뷰의 각 세그먼트가 반대로 표시되는 문제를 해결하였습니다.
| 문제 상황 | 수정 후 |
|    <img src="https://github.com/user-attachments/assets/634ee335-2408-4fc6-be20-a1900e444bf0" width=250>    |   <img src="https://github.com/user-attachments/assets/e612e6eb-532d-4192-b8c2-4229950ec049" width=250>  |
=> [Fix] #554 - 장소 목록 뷰의 각 세그먼트가 반대로 표시되는 문제 해결

Offroad-iOS/Offroad-iOS/Global/Components/Overlay/LogPrinter/PrintLogInDevApp.swift, Offroad-iOS/Offroad-iOS/Network/Base/NetworkResultError.swift, Offroad-iOS/Offroad-iOS/Network/Base/NetworkResultHandler.swift
- #550 
자잘한 변경점들입니다.
- 개발용 Target의 로그 콘솔을 띄우는 전역 함수 printLog에서 `print()` 도 같이 출력하도록 했습니다ㅏ.
- NetworkResultError 중 decodingFailed의 에러 메시지를 출력할 때, 디코딩이 실패한 DTO 타입도 같이 출력하도록 했습니다.
|뷰|설명|
- Resolved: #550
=> [Chore] #550 - 자잘한 코드 개선

Offroad-iOS/Offroad-iOS/Presentation/ORBRecommendation/chat/Views/ORBRecommendationChatExampleQuestion.swift
- #566 
- 오브의 추천소 채팅 뷰에서 예시 질의 버튼의 디자인을 개선하였습니다.  
- 행간 설정(160%)
- 여러 단어에 볼드처리(다른 폰트 적용) 가능하도록 변경
- 오브의 추천소 채팅 뷰에서 예시 질의 문구를 변경하였습니다.
변경사항이 많지 않아, 위 변경사항들을 하나의 커밋으로 반영하였으니, 참고 바랍니다. 
|뷰|설명|
|  <img src="https://github.com/user-attachments/assets/94177978-1cdd-4fcc-9d55-7da75dd432a0" width=250>   |   <img src="https://github.com/user-attachments/assets/019e5c47-fd5c-4351-a2da-5c1481af7eb9" width=250>  |
- Resolved: #566
=> [Feat] #566 - 추천소 채팅 뷰에서 예시 질의 버튼 디자인 개선

Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj, Offroad-iOS/Offroad-iOS/Global/Components/ORBMap/ORBMapView.swift, Offroad-iOS/Offroad-iOS/Global/Components/ORBMap/PlaceInfoTooltip/PlaceInfoTooltip.swift, Offroad-iOS/Offroad-iOS/Global/Protocols/PlaceProtocols.swift, Offroad-iOS/Offroad-iOS/Network/Adventure/DTO/Response/AdventuresPlaceAuthenticationResponsetDTO.swift, Offroad-iOS/Offroad-iOS/Network/Base/NetworkService.swift, Offroad-iOS/Offroad-iOS/Network/ORBRecommendation/DTO/Request/ORBRecommendationChatRequestDTO.swift, Offroad-iOS/Offroad-iOS/Network/ORBRecommendation/DTO/Response/ORBRecommendationChatResponseDTO.swift, Offroad-iOS/Offroad-iOS/Network/ORBRecommendation/DTO/Response/ORBRecommendationFixedPhraseResponseDTO.swift, Offroad-iOS/Offroad-iOS/Network/ORBRecommendation/DTO/Response/ORBRecommendationPlacesResponseDTO.swift, Offroad-iOS/Offroad-iOS/Network/ORBRecommendation/DTO/Response/ORBRecommendationResponseDTO.swift, Offroad-iOS/Offroad-iOS/Network/ORBRecommendation/ORBRecommendationAPI.swift, Offroad-iOS/Offroad-iOS/Network/ORBRecommendation/ORBRecommendationService.swift, Offroad-iOS/Offroad-iOS/Network/Place/DTO/Responce/RegisteredPlaceResponseDTO.swift, Offroad-iOS/Offroad-iOS/Presentation/ORBRecommendation/chat/ViewControllers/ORBRecommendationChatViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/ORBRecommendation/chat/Views/ORBRecommendationChatView.swift, Offroad-iOS/Offroad-iOS/Presentation/ORBRecommendation/main/ViewController/ORBRecommendationMainViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/ORBRecommendation/main/Views/ORBRecommendationMainView.swift, Offroad-iOS/Offroad-iOS/Presentation/ORBRecommendation/main/Views/ORBRecommendedContentView.swift, Offroad-iOS/Offroad-iOS/Presentation/ORBRecommendation/model/ORBRecommendationPlaceModel.swift, Offroad-iOS/Offroad-iOS/Presentation/PlaceList/Model/PlaceModel.swift, Offroad-iOS/Offroad-iOS/Presentation/PlaceList/Views/PlaceCollectionViewCell.swift, Offroad-iOS/Offroad-iOS/Presentation/PlaceList/Views/PlaceListCell.swift, Offroad-iOS/Offroad-iOS/Presentation/QuestMap/Model/AdventureResult.swift, Offroad-iOS/Offroad-iOS/Presentation/QuestMap/UIComponents/PlaceMapMarker.swift, Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/AdventureMapViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewModel/AdventureMapViewModel.swift
- #546
다른 네트워크 서비스와 거의 동일한 형태입니다. 
다음 기능들을 가집니다.
- 오브의 추천소 상단 (그라데이션 버튼)문구를 받아오는 기능
- 오브의 추천 장소 목록을 조회하는 기능
- 오브의 추천소 채팅을 보내는 기능
- 오브의 추천소 기능을 구현하면서 '오브가 추천해준 장소' 를 나타낼 별도 데이터 모델을 정의해야 했습니다.  
거의 비슷한 형식인데 조금씩 속성들이 달라서..
그리고 코스퀘스트 장소를 나타낼 데이터 모델의 속성도 기존 PlaceModel과는 크게 차이가 있는 것 같아서
장소 목록 셀이나 마커에서 장소 정보를 갖거나 이용하는 경우가 있는데요, 이때 탐험 시 사용되는 장소 모델과 추천소에서 사용되는 장소 모델 타입에 대해 일일이 분기처리할 경우 불필요한 코드가 너무 많아질 것 같아서, 장소 모델 자체를 추상화하였고, 
구체 타입이 필요 시 타입캐스팅을 통해 분기처리할 수 있도록 하였습니다. 
``` swift
//  장소를 나타내는 데이터 모델의 인터페이스.
import CoreLocation
/// '장소'를 나타내는 데이터가 필수로 가져야 하는 속성들을 포함하는 타입.
protocol BasePlaceType {
/// 장소 이름
var name: String { get }
/// 장소의 주소
var address: String { get }
/// 장소의 카테고리. `ORBPlaceCategory` 타입
var placeCategory: ORBPlaceCategory { get }
/// 장소의 위•경도 좌표
var coordinate: …
```
=> [Feat] #546 - 오브의 추천소 채팅 및 추천 장소 업데이트 기능 구현
