Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj, Offroad-iOS/Offroad-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- #1 
SPM 설치
- SnapKit
- Moya
- Kingfisher
- kakaoSDK
- Resolved: #1
=> [Add] #1 - SPM 설치

.gitignore, Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
- #22 
협업 시에 생기는 충돌을 방지하기 위해 추가적인 환경설정을 하였습니다. 
- iOS 최소 배포 버전 17 -> 15로 변경
- .gitignore에 파일 추가
- .DS_Store
- Package.resolved
- 가로모드 안되게 제한
pull 받은 후에 git의 추적을 피하기 위해, Package.resolved 파일과 .DS_Store 파일을 삭제해 주세요!
- Resolved: #22
=> [Setting] #22 - 프로젝트 환경설정 추가 세팅

Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj, Offroad-iOS/Offroad-iOS/Global/Components/CustomButton/OffroadButton.swift
- #35 
|닉네임 설정 뷰|칭호 변경 뷰|
|:---:|:---:|
|<img width="538" alt="image" src="https://github.com/Team-Offroad/Offroad-iOS/assets/111677378/1106325b-b1fc-4a2a-84e3-852410d8f6d7">|<img width="497" alt="image" src="https://github.com/Team-Offroad/Offroad-iOS/assets/111677378/894ab3a5-c463-48c9-85fe-2535d29c44cb">|
- 위 두 부분에 들어갈 버튼이 텍스트 입력 여부, 칭호 선택 여부에 따라 실시간으로 변경되어야 하기 때문에 CustomButton을 구현하였습니다.
- 일반 UIButton처럼 사용하되 따로 속성들을 잡아줄 필요없이 선언할 때 지정하는 titleLabel의 text와 AutoLayout만 추가해주면 됩니다!
`private let button: OffroadButton = OffroadButton(state: .isEnabled, title: "다음")` 이런 식으로 사용하면 됩니당~~
|적용 화면|
|:------:|
|<img width="303" alt="image" src="https://github.com/Team-Offroad/Offroad-iOS/assets/111677378/4bfb4c6f-1ace-4c2f-a431-2468aab2141d">|
- Resolved: #35
=> [Feat] #35 - Custom Button 구현

Offroad-iOS/Offroad-iOS/Network/Auth/DTO/Response/SocialLoginResponseDTO.swift, Offroad-iOS/Offroad-iOS/Presentation/Login/ViewController/LoginViewController.swift
- #71
서버 API 변경 사항 반영하여 로그인 이력 조회 및 화면 전환 로직 변경하였습니다!
캐릭터 생성이 완료되지 않으면 홈뷰로 넘어가지 않도록 수정하였습니다.
- Resolved: #71
=> [Fix/#71] 로그인 이력 조회 및 화면 전환 로직 변경 반영

Offroad-iOS/Offroad-iOS/Network/Profile/DTO/Request/ProfileUpdateRequestDTO.swift, Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/BirthViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/GenderViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
- #81 
- 생년월일 입력 뷰 버튼 layer 컬러 없애기
- 생년월일 유효성 검사 구현 및 수정
- 중복 확인 누르면 키보드 내려가게 구현
|뷰|설명|
=> [Chore] #81 - 

Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj, Offroad-iOS/Offroad-iOS/Application/SceneDelegate.swift, Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Profile/Contents.json, Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/backBarButton.imageset/Contents.json, Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/backBarButton.imageset/backBarButton.svg, Offroad-iOS/Offroad-iOS/Presentation/Nickname/View/BirthView.swift, Offroad-iOS/Offroad-iOS/Presentation/Nickname/View/GenderView.swift, Offroad-iOS/Offroad-iOS/Presentation/Nickname/View/NicknameView.swift, Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/BirthViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/GenderViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
- #83 
- UINavigationBar의 뒤로가기 버튼 커스텀
- "다음" 버튼에 Component 적용하여 리팩토링
|뷰|설명|
=> [Feat] #83 - 

Offroad-iOS/Offroad-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved, Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/BirthViewController.swift
- #88 
튼 isenabled 수정사항 반영
|뷰|설명|
=> [Chore] #88 - 버튼 isenabled 수정사항 반영

Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/BirthViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/GenderViewController.swift
- #90 
커스텀한 백버튼을 회원가입 전체 VC에 적용
|뷰|설명|
- Resolved: #90
=> [Feat] #90 - 커스텀 백버튼 전체 적용

Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
- #94 
닉네임 입력 뷰에서 중복확인 버튼이 활성화 되었을 때 layer 없게 수정
|뷰|설명|
- Resolved: #94
=> [Feat] #94 - 중복확인 활성화 됐을 때 layer 없애기

Offroad-iOS/Offroad-iOS/Presentation/QuestMap/Views/PlaceInfoPopupView.swift, Offroad-iOS/Offroad-iOS/Presentation/QuestMap/Views/QuestMapView.swift, Offroad-iOS/Offroad-iOS/Presentation/TabBar/ViewControllers/OffroadTabBarController.swift
- #100 
100번째 이슈!!!!
QA 2차 후 세부적인 수정 사항들 반영하였습니다!
앱잼 기간 수고 많으셨습니다!!
|뷰|설명|
=> [Fix] #100 - QA 2차 수정 후 자잘한 수정

Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
- #106 
textfield 선택 시에도 layer 색 변경되도록 수정
|뷰|설명|
=> [Fix/#106] textfield 선택 시 layer 색 변경

Offroad-iOS/Offroad-iOS/Presentation/Nickname/View/BirthView.swift, Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/BirthViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
- #116 
- 생년월일 실시간 유효성 검사
- 생년월일 자동이동 로직 수정
- 다음 버튼 로직 수정
- 에러메세지 색상 변경 
|뷰|설명|
- Resolved: #116
=> [Fix] #116 - 생년월일 실시간 유효성 검사 및 자동이동과 다음 버튼  로직 수정

Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/QuestMapViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/QuestMap/Views/QuestMapView.swift, Offroad-iOS/Offroad-iOS/Presentation/QuestResult/Views/QuestResultView.swift
- #118 
다음 사항들을 수정하였습니다. 
빌드하여 다음 항목들을 체크해 주세요.
(시간이 부족해 GIF 파일을 같이 올리지 못하는 점 양해 바랍니다..ㅠ)
- 지도에 뜨는 장소 마커를 누를 시 특정 배율로 줌인/줌아웃 되는 현상을 없앴습니다. 
- 해당 줌인/줌아웃 기능은 추후 기획 및 안드 파트와 논의하여 수정될 수 있습니다.
- 현 위치 버튼(지도 우측 상단 버튼)을 눌렀을 때의 동작을 기능명세서에 적힌 대로 구현하였으며,  
기능명세서에 적힌 (버튼이 눌렸을 때의) 동작은 다음과 같습니다. 
- 논 팔로워 상태 -> 팔로워 상태, 팔로워 상태 -> 논 팔로워 상태
- 지도 뷰에 현 위치 마커가 없을 경우 현 위치 마커로 이동
- QR 인증이 성공했을 때 팝업창이 뜨면 배경을 어둡게 설정하였습니다. 
- 추후 개선할 예정입니다. 
|뷰|설명|
=> [Fix] #118 탐험 관련 QA 수정(1차)

Offroad-iOS/Offroad-iOS/Global/Literals/ColorLiterals.swift, Offroad-iOS/Offroad-iOS/Presentation/Character/ChoosingCharacter/View/ChoosingCharacterView.swift, Offroad-iOS/Offroad-iOS/Presentation/Character/CompleteChoosingCharacter/View/CompleteChoosingCharacterView.swift, Offroad-iOS/Offroad-iOS/Presentation/Home/TitlePopup/View/Cell/TitleCollectionViewCell.swift, Offroad-iOS/Offroad-iOS/Presentation/Home/TitlePopup/View/TitlePopupView.swift, Offroad-iOS/Offroad-iOS/Presentation/Home/TitlePopup/ViewController/TitlePopupViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Home/ViewController/HomeViewController.swift
- #119 
- 디자인 컬러 스타일 가이드 추가된 색상 ColorLiterals에 추가하였습니다.
- 캐릭터 선택 완료 시 기존에 CharacterImageView를 초기화할 때 넣어두었던 이미지가 잠깐 보이는 현상 해결하였습니다.
- 칭호 선택 팝업에서 사용자의 칭호가 이미 선택되어있는 상태로 변경한 후, 현재 칭호는 선택이 불가능하도록 수정하였습니다.
|칭호 선택 화면|
|:------:|
| https://github.com/user-attachments/assets/f53e3956-4b39-4cb7-9ccf-2b57a809d879 |
- Resolved: #119
=> [Fix] #119 - ChoosingCharacterView, HomeView QA 수정사항 반영

Offroad-iOS/Offroad-iOS/Presentation/MyPage/Character/Cell/AcquiredCharactersCell.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/Character/ViewController/AcquiredCharactersViewController.swift
- #133 
|뷰|설명|
- Resolved: #133
=> [Fix/#133] 코드리뷰 최종 반영

Offroad-iOS/Offroad-iOS/Global/Resources/Info.plist
- #148 
위치, 카메라 사용 권한 요청 시 문구가 기존에는 임시로 적은 문구들이었습니다. 
이 문구들을 기획 측에서 전달받은 공식 문구로 교체하였습니다. 
위치 정보 조회 시 500 코드 에러가 떠서 현재 위치 정보가 조회되지 않는 상황인 것 같습니다. 
때문에 카메라 접근 권한 여부는 확인하지 못했으나, 아마 제대로 동작하리라 예상합니다. 
| 뷰 | <img src="https://github.com/user-attachments/assets/b1117681-fe62-4cc3-b6d5-c2fded8e99ed" width=200> |
| 설명 | 문구가 제대로 뜨는 것 확인함 |
- Resolved: #148
=> [Fix/#148] 권한 요청 문구(위치, 카메라) 변경

Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
- #181
RxSwift, RxCocoa, RxRelay 를 사용할 수 있도록 하였습니다.
|뷰|설명|
- Resolved: #181
=> [Setting] #181 - RxSwift, RxCocoa, RxRelay 라이브러리 추가

Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
- #186 
RxSwift, RxCocoa, RxRelay 라이브러리 실행에 문제가 있어, 이를 사용할 수 있도록 다시 추가하였습니다.
|뷰|설명|
- Resolved: #186
=> [Setting/#186] RxSwift, RxCocoa, RxRelay 사용할 수 있도록 추가

Offroad-iOS/Offroad-iOS/Presentation/TabBar/ViewControllers/OffroadTabBarController.swift
- #219 
일부 iOS 버전에서 탭바가 내려갈 때 이상하게 내려가는 문제를 해결하였습니다. 
iOS 18.0 이상의 버전에서 해당 현상이 발생합니다. iOS 18.0 이상의 기기나 시뮬레이터에서 테스트해 주세요
|   <img src="https://github.com/user-attachments/assets/a638f621-1381-40f0-a845-741afcfde645" width=150>  |    <img src="https://github.com/user-attachments/assets/3b968011-f986-4248-a0b1-84913fe59258" width=150>   |
|:---:|:---:|
|  수정 전  |  수정 후  |
- Resolved: #219
=> [Fix/#219] 일부 iOS 버전에서 탭바가 숨겨질 때 이상하게 보이는 문제 해결

Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/QuestMapViewController.swift
- #248 
지도 뷰에서 발견된 버그를 해결하였습니다. 
지도 뷰에서 위치 모드가 방향도 트래킹할 때(기기 방향에 맞게 지도가 돌아가는 경우)
지도상의 마커를 터치하여 툴팁이 나타난 경우, 나타난 후에서 지도가 기기 방향에 맞게 계속 돌아가던 버그를 해결하였습니다.
|뷰|설명|
- Resolved: #248
=> [Fix] #248 - 지도 버그 해결

Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj, Offroad-iOS/Offroad-iOS/Network/Base/NetworkService.swift, Offroad-iOS/Offroad-iOS/Network/CharacterChat/CharacterChatAPI.swift, Offroad-iOS/Offroad-iOS/Network/CharacterChat/CharacterChatService.swift, Offroad-iOS/Offroad-iOS/Network/CharacterChat/DTO/Request/CharacterChatPostRequestDTO.swift, Offroad-iOS/Offroad-iOS/Network/CharacterChat/DTO/Response/CharacterChatGetResponseDTO.swift, Offroad-iOS/Offroad-iOS/Network/CharacterChat/DTO/Response/CharacterChatPostResponseDTO.swift
- #276 
캐릭터 채팅 관련 API 코드를 작성하였습니다. 
현재 서버에서 이슈가 있어 정상적인 응답을 받아오지 못하는 상태이나, 미리 작성해두어 후에 캐릭터 채팅 UI 구현에 사용할 예정입니다. 
|뷰|설명|
- Resolved: #276
=> [Feat] #276 - CharacterChatAPI 구현

Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/Cell/CharacterDetailCell.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/View/CharacterDetailView.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/View/MyPageView.swift
- #311 
캐릭터 상세 뷰의 UI를 개선하였습니다. 
기능적인 차이는 없습니다.
개선 전/후 차이는 하단의 스크린샷 항목을 참고해 주세요!
|개선 전|개선 후|
|   <img src="https://github.com/user-attachments/assets/6f0c0cba-34e5-4fe0-b62d-a66356f67ebc" width=200>   |   <img src="https://github.com/user-attachments/assets/b908b00e-cb27-431d-bd51-77e299eedbab" width=200> |
- Resolved: #311
=> [Fix] #311 - 캐릭터 상세 뷰의 UI 개선

Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj, Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/CouponListViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/PlaceList/ViewControllers/PlaceListViewController.swift
- #328 
`ORBSegmentedControl`과 연관된 pageViewController이 제스처에 의해 스크롤 중일 때(스크롤하다 중간에 멈춰 있는 경우 포함) 
Segment를 탭 하면 이상하게 동작하는 문제가 있었습니다. 
이를 해결하기 위해 `ORBSegmentedControl`과 연결된 PageViewController가 (제스처에 의한) 스크롤을 시작할 때 
segmentedControl의 터치 입력을 제한하고, 
스크롤이 끝나면 segmentedControl의 터치 입력을 다시 활성화하였습니다.
|뷰|설명|
- Resolved: #328
=> [Fix] #328 - ORBSegmentedControl에서 스크롤 중에 Segment를 탭 하면 이상하게 동작하는 문제

Offroad-iOS/Offroad-iOS/Presentation/Home/ViewController/HomeViewController.swift
- #358
기존의 id를 인덱스에 넣어서 화면이 넘어가던 방식에서 id 값을 조회하여 일치하면 넘어가는 방식으로 변경하였습니다.
- Resolved: #358
=> [Fix] #358 - 공지사항 푸시 리다이렉션 로직 수정

Offroad-iOS/Offroad-iOS/Global/Extensions/String+.swift, Offroad-iOS/Offroad-iOS/Network/Profile/DTO/Request/ProfileUpdateRequestDTO.swift, Offroad-iOS/Offroad-iOS/Presentation/Character/ChoosingCharacter/ViewController/ChoosingCharacterViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Nickname/View/NicknameView.swift, Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/BirthViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/GenderViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
- #387 
- 중복 닉네임 textfield layer 에러 색상 적용
- GenderVC로 건너뛰기 후 backButton 눌렀을 때 BirthVC textfield 초기화
- 프로필 업데이트 api 수정사항 DTO에 반영
- 캐릭터 선택 뷰에서 patch 요청 보내도록 수정
- totalEUCKRByteCount 적용 시도와 문제상황 주석처리
```swift
///기존에 성별 선택 뷰에서 요청 보내던 걸 캐릭터 선택 뷰에서 patch 요청 보내도록 수정했다.
//ChoosingCharacterViewController.swift
private func patchProfileData(characterID: Int) {
//생략
ProfileService().patchUpdateProfile(body: ProfileUpdateRequestDTO(nickname: nickname, year: birthYear, month: birthMonth, day: birthDay, gender: gender, characterID: characterID)) { result in
switch result {
case .success(let response):
print("프로필 업데이트 성공~~~~~~~~~")
let choosingCharacterViewController = ChoosingCharacterViewController()
let customBackBarButton = UIBarButtonItem(customView: button) …
```
=> [Fix] #387 - 온보딩 뷰 2차 QA 수정사항 적용

Offroad-iOS/Offroad-iOS/Presentation/Nickname/View/NicknameView.swift, Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/GenderViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
- #398 
3차 QA 후 안드와 싱크를 맞추기 위한 수정사항 적용과 온보딩 리팩토링 이후 누락된 로직 추가입니다.
- 닉네임 뷰 formError가 아닌 닉네임일 때 중복 버튼 누르기 전엔 에러메세지가 사라지는 게 아니라 "*한글 2~8자, 영어 2~16자 이내로 작성해주세요."가 뜨도록 수정
- 닉네임 뷰 hintText "닉네임을 입력" -> "닉네임 입력"으로 수정
- 닉네임 뷰 layer 색상 초기 상태의 경우(`isTextFieldEmpty && isInitialState`)와 값을 지워서 `isTextFieldEmpty`인 상황을 분리
- 중복 닉네임일 때의 layer 색상 변경
- 성별 뷰 선택 해제 가능하게 수정
- 중복 닉네임일 때 textfield를 선택할 때가 아닌 수정할 때만 borderColor가 main2가 되도록 수정
기존에 BehaviorRelay로 버튼 상태를 파악하는 방식은 같다. 하지만 기존 메소드는 BehaviorRelay가 버튼이 “선택”된 것만 파악하여 UI를 변경했기 때문에 버튼을 다시 선택하여 해제했을 때의 UI 변경이 적용이 안되는 문제가 있었다. 따라서 UI 변화를 관리하는 메소드 `updateGenderButtonStates`를 따로 만들었다.
1. `toggleGenderSelection` 메서드는 선택된 버튼의 상태를 토글하고 나머지 버튼을 초기화
2. BehaviorRelay의 상태를 업데이트한 후 `updateGenderButtonStates`를 호출하여 버튼의 UI를 업데이트
3. `updateGenderButtonStates`는 각 버튼의 …
=> [Fix] #398 - 3차 QA 온보딩(닉네임, 생년월일, 성별 뷰) 수정사항 적용

Offroad-iOS/Offroad-iOS/Presentation/Home/View/HomeView.swift, Offroad-iOS/Offroad-iOS/Presentation/Home/ViewController/HomeViewController.swift
- #396
- 로티 발동 조건 수정
- 로티 반복 횟수 지정
- 로티 및 상단 버튼 이미지 사이즈 수정
|뷰|설명|
- Resolved: #396
=> [Fix] #396 - 홈 화면 기본 로티 적용

Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/ORBMapViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewModel/ORBMapViewModel.swift, Offroad-iOS/Offroad-iOS/Presentation/QuestMap/Views/ORBMapView.swift
- #431 
지도 시점이 기울어진 상황에서 툴팁이 뜰 때 가려지는 문제를 방지하기 위해서, 로직을 개선하였습니다.
지도의 시점이 수직 방향에 가까울 때에는 기존과 변경이 없습니다. 
지도의 시점이 기울어진 상황에서 툴팁이 뜰 때에는 마커가 지도의 중심에 오도록 변경하였습니다.
| before | after |
| <img src="https://github.com/user-attachments/assets/61800448-6816-4582-b356-21f38312686a" width=250>   | <img src="https://github.com/user-attachments/assets/cbeb476d-9c54-44e8-afd3-f835fa2d9d28" width=250>  |
- Resolved: #431
=> [Chore] #431 - 지도의 시점이 기울어진 상황에서 툴팁이 뜰 때 가려지는 문제 해결

Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/ORBCharacterChatManager.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/ViewControllers/ORBCharacterChatViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/Views/ORBCharacterChatBox.swift, Offroad-iOS/Offroad-iOS/Presentation/Home/ViewController/HomeViewController.swift
- #440 
채팅 시에 캐릭터 채팅 박스 관련 코드를 정리하였습니다. 리팩토링이라고 적긴 하였으나, 실질적으로 리팩토링보다는 거의 코드 정리 수준이라고 봐 주시면 될 것 같습니다. 
- `ORBCharacterChatViewController`에서 코드가 너무 많고 복잡하여, 문제가 발생할 때 코드를 찾기 어려운 것 같다는 느낌을 많이 받았습니다. 
그래서 원래는 채팅창에서 캐릭터 채팅  박스 (화면 상단에서 내려오는 토스트처럼 동작하는 뷰) 의 동작을 별도의 타입을 만들어서 분리하고자 하였는데, 생각해보면 캐릭터 채팅 창의 동작은 뷰컨트롤러에서 일어나는 핵심 기능이기도 하고 현재로서는 재사용의 필요성을 크게 느끼지 못해 별도의 타입으로 빼지는 않았습니다. 
- 뷰컨트롤러의 역할이 너무 커지는 것을 막기 위해서 뷰컨트롤러에 정의되어있던 메서드 일부를 채팅 박스 타입으로 이동하였습니다. 
- `ORBCharacterChatViewController`의 코드를 정리하였습니다. 
해당 타입의 메서드를 크게 세 종류로 분류하였습니다. 분류한 항목은
1)채팅창 입력 관련 함수, 2)채팅 박스 관련 함수, 3)기타
입니다.
이 중 2) 와 3) 을 확장을 통해 분리하여 조금 더 코드를 보기 편하도록 배치하였습니다. 
대략적으로 설명하면 `ORBCharacterChatViewController.swift` 파일은 대략적인 형식은 다음과 같습니다. 
``` swift 
class ORBCharacterChatViewController: UIViewController {
//MARK: - Properties
/* …
```
=> [Refactor] #440 - ORBCharacterChatViewController 정리

Offroad-iOS/Offroad-iOS/Presentation/QuestMap/UIComponents/ORBNMFMarker.swift
- #447 
보다 자연스러운 표시를 위해
지도 마커의 아이콘에 원근감을 적용하였습니다. 
`NMFMarker` 의 속성인 `iconPerspectiveEnabled` 의 값에 `true`를 할당해 주었습니다. 
| 전 | 후 |
|    <img src="https://github.com/user-attachments/assets/f4515adb-bf86-4626-ac64-b4750aed198b" width=250>    |   <img src="https://github.com/user-attachments/assets/0534a072-c918-497c-ba53-6c2f40fdca57" width=250>  |
- Resolved: #447
=> [Feat/#447] 마커 아이콘에 원근감 적용

Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj, Offroad-iOS/Offroad-iOS/Application/AppDelegate.swift, Offroad-iOS/Offroad-iOS/Global/Amplitude/AmplitudeManager.swift, Offroad-iOS/Offroad-iOS/Global/Resources/Info.plist, Offroad-iOS/Offroad-iOS/Global/Resources/Info_Dev.plist, Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewModel/ORBMapViewModel.swift
- #493 
Amplitude가 배포용 앱에서만 동작하도록 변경하였습니다.
(기존에는 개발용 앱에서만 동작했었습니다.)
이에 따라
Info_Dev.plist에서 AMPLITUDE_API_KEY 항목을 제거하고,
Info.plist 에서 AMPLITUDE_API_KEY 항목을 추가했습니다.
SecretConfig 및 SecretConfig_Dev 파일에서도 똑같이 반영해주시면 됩니다.
|뷰|설명|
- Resolved: #493
=> [Feat] #493 - Amplitude 배포 환경에서만 동작

Offroad-iOS/Offroad-iOS/Global/Extensions/UIView+.swift, Offroad-iOS/Offroad-iOS/Presentation/Diary/ViewController/DiaryViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/MemoryLight/ViewController/MemoryLightViewController.swift
- #498
기억빛 공유하기 기능을 구현했습니다.
- UIView를 UIImage로 변환하는 UIView+ extension을 추가했습니다.
|iPhone 16|iPhone SE|
|:------:|:------:|
|<img src = "https://github.com/user-attachments/assets/cce5d41c-8e09-4b8b-9f3e-f9c30017dcf2" width ="280">|<img src = "https://github.com/user-attachments/assets/b57d1b2a-687f-41ad-9793-ff1ff1e809d8" width ="280">|
- Resolved: #498
=> [Feat] #498 - 기억빛 공유하기 기능 구현

Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj, Offroad-iOS/Offroad-iOS/Global/Components/Overlay/Alert/AlertView/ORBAlertBaseView.swift, Offroad-iOS/Offroad-iOS/Global/Literals/StringLiterals.swift, Offroad-iOS/Offroad-iOS/Presentation/ORBRecommendation/main/ViewController/ORBRecommendationMainViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/ORBRecommendation/order/ORBRecommendationOrderView.swift, Offroad-iOS/Offroad-iOS/Presentation/ORBRecommendation/order/ORBRecommendationOrderViewController.swift
- #519
- "주문서 작성 완료" 버튼의 동작은 서버 API 가 나오면 관련 데이터 형식과 묶어 같이 구현할 예정입니다. (현재는 '주문서 작성 완료' 버튼의 동작은 별도 구현되어 있지 않습니다.)
|뷰|설명|
|   <img src="https://github.com/user-attachments/assets/9f35db5d-bfd8-4c49-8a59-e3db0f9a3164" width=250>     |   <img src="https://github.com/user-attachments/assets/8bfe3e58-ec1d-4428-af32-1872d2842574" width=250>  |
- Resolved: #519
=> [Feat] #519 - 오브의 추천 주문서(2안) GUI 구현

Offroad-iOS/Offroad-iOS/Global/Components/SegmentedControl/ORBSegmentedControl.swift, Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/CouponListViewController.swift, Offroad-iOS/Offroad-iOS/Presentation/PlaceList/ViewControllers/PlaceListViewController.swift
- #540 
- 내부적으로 함수를 개선하고 기능별로 재배치했습니다.
- 각 함수별로 주석을 추가하였습니다.
- 새 기능을 추가했습니다.
- `underbar`의 위치를 직접 할당 가능.
- `setUnderbarPosition(process:)` 메서드로 사용할 수 있습니다.
- 새로 추가된 기능을 사용하여 따라 장소 목록 뷰, 쿠폰 목록 뷰에서 가로 스크롤을 통해 segment 사이를 오갈 시 `underbar`가 실시간으로 위치를 따라오도록 구현하였습니다.
|장소 목록 뷰|쿠폰 목록 뷰|
|    <video src="https://github.com/user-attachments/assets/719a523d-9812-4151-ba75-e4ed6035c79b" width=300>   |   <video src="https://github.com/user-attachments/assets/383c8014-dc58-4d05-8da5-db4058ad8d62" width=300>  |
- Resolved: #540
=> [Refactor] #540 - ORBSegmentedControl 리팩토링 및 기능 추가
